SPOOL 01_AACI_tablas.log
	
	DEF USUARIO=AACID_OWNER;
    DEF TABLESPACE_DATOS=TS_D_AACID_OWNER;

	CREATE TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD
	(
	ID_SOLICITUD  NUMBER (19) CONSTRAINT AACI_SOLICITUDID_CK NOT NULL,
	NU_NUMEXPEDIENTE NUMBER (19) NOT NULL,
	NU_NUMINTERNO NUMBER (19) NOT NULL,
	TX_PERSONANOTIF VARCHAR2 (20 CHAR),
	TX_REPETAGRUP1RACDA VARCHAR2 (50 CHAR),
	TX_SOLI1MEDNOTIFORD VARCHAR2 (250 CHAR),
	TX_REPETAGRUP2SIGLAS VARCHAR2 (250 CHAR),
	TX_SOLI1APELLIDO1  VARCHAR2 (50 CHAR),
	TX_REPR1NOMBRE VARCHAR2 (50 CHAR),
	TX_SOLI1APELLIDO2 VARCHAR2 (50 CHAR),
	TX_AGRUPREPNOMBRE VARCHAR2 (150 CHAR),
	FH_AUTORIZAGEST1OTRASFEC TIMESTAMP,
	TX_AUTORIZAGEST1OTRASDOC VARCHAR2 (80 CHAR),
	TX_SOLI1PISO VARCHAR2 (20 CHAR),
	TX_FIRM1ANO VARCHAR2(10 CHAR),
	TX_REPDATOS1EJECUCION VARCHAR2(20 CHAR),
	TX_NOTIFTELEFONOAUTLUGAR VARCHAR2(20 CHAR),
	TX_AUTORIZAGEST1OTRASPRO VARCHAR2 (80 CHAR),
	NU_SOLICITADASOLIMPORTE NUMBER (20,2),
	LG_CHECKDOC1 NUMBER(1) default 0,
	TX_REPR1SEXO VARCHAR2(10 CHAR),
	TX_SOLI1SIGLAS VARCHAR2(20 CHAR),
	LG_CHECKDOC2 NUMBER(1) default 0,
	TX_CONCEDIDASCONADMIN VARCHAR2 (80 CHAR),
	LG_CHECKDOC3 NUMBER(1) default 0,
	NU_FIRM1IMPORTE NUMBER (20, 2),
	LG_CHECKDOC4 NUMBER(1) default 0,
	LG_CHECKDOC5 NUMBER(1) default 0,
	LG_CHECKDOC6 NUMBER(1) default 0,
	LG_CHECKDOC7 NUMBER(1) default 0,
	LG_CHECKDOC8 NUMBER(1) default 0,
	TX_NOTIFNUMIDENTLUGAR VARCHAR2 (250 CHAR),
	LG_CHECKDOC9 NUMBER(1) default 0,
	TX_REPETAGRUPRACDA VARCHAR2 (50 CHAR),
	LG_SOLI1ALTANOTIFICA NUMBER(1) default 0,
	TX_REPETAGRUP2RACDA VARCHAR2 (50 CHAR),
	TX_SOLI1NUMIDENT VARCHAR2 (50 CHAR),
	TX_FIRM1FDO VARCHAR2 (4000 CHAR),
	FH_AUTOJUNTA1ADMFECHA TIMESTAMP,
	TX_SOLICITADAS0ADMIN VARCHAR2 (80 CHAR),
	TX_AUTORIZAGEST0OTRASDOC VARCHAR2 (80 CHAR),
	TX_AUTORIZAJUNTA0ADMDOC VARCHAR2 (80 CHAR),
	TX_AGRUPREPAPELLIDO2 VARCHAR2 (250 CHAR),
	LG_ALTANOFIFICA NUMBER (1) default 0,
	TX_AGRUPREPAPELLIDO1 VARCHAR2 (50 CHAR),
	TX_REPETAGRUPNOMBRE VARCHAR2 (150 CHAR),
	TX_SOLICITADAS1MINIMIS VARCHAR2 (50 CHAR),
	TX_AGRUPREPIDENTIFIC VARCHAR2 (10 CHAR),
	TX_FIRM1DIA VARCHAR2(10 CHAR),
	TX_SOLICITADAS0FECHA VARCHAR2(20 CHAR),
	TX_CODIDENTIFICATIVO VARCHAR2 (50 CHAR),
	TX_REPR1TIPOVIA VARCHAR2 (10 CHAR),
	TX_REPETAGRUP2NOMBRE VARCHAR2 (4000 CHAR),
	TX_SOLI1EMAIL VARCHAR2 (250 CHAR),
	TX_SOLI1NUMERO VARCHAR2(20 CHAR),
	TX_SOLI1CODMUNICIPIO VARCHAR2(20 CHAR),
	TX_DATOSTITULO VARCHAR2 (100 CHAR),
	TX_CONCEDIDAS0MINIMIS VARCHAR2 (10 CHAR),
	TX_REPETAGRUP1SIGLAS VARCHAR2 (20 CHAR),
	TX_REPR1NOMBREVIA VARCHAR2 (100 CHAR),
	TX_AUTORIZAJUNTA1ADMCONS VARCHAR2 (80 CHAR),
	TX_ERRORFINALIDADPROY VARCHAR2 (250 CHAR),
	TX_NOTIFEMAILAUTLUGAR VARCHAR2 (250 CHAR),
	TX_REPR1TIPOIDENT VARCHAR2 (50 CHAR),
	TX_SOLICITADAS0MINIMIS VARCHAR2 (10 CHAR),
	NU_SOLI1TLFMOVIL NUMBER (9),
	TX_REPR1TITULO VARCHAR2(50 CHAR),
	NU_SOLI1CP NUMBER (5),
	TX_REPETAGRUP1IDENT VARCHAR2 (50 CHAR),
	FH_CONCEDIDAS1FECHA TIMESTAMP,
	NU_REPR1CODPROV NUMBER(2),
	TX_SOLI1POBLACION VARCHAR2 (50 CHAR),
	LB_TEXTOOTRAAS CLOB,
	TX_SOLI1NOMBREVIA VARCHAR2 (100 CHAR),
	TX_REPDATOS0EJECUCION VARCHAR2(20 CHAR),
	TX_SOLI1ESCALERA VARCHAR2 (50 CHAR),
	TX_REPET0AGRUPIDENTIF VARCHAR2 (50 CHAR),
	TX_SOLI1SEXO VARCHAR2 (10 CHAR),
	LG_CHECKDOC20 NUMBER(1) default 0,
	TX_SOLI1PORTAL VARCHAR2 (50 CHAR),
	LG_CONSENTEXPRESOREPR NUMBER (1) default 0,
	TX_SOLI1CODIGO VARCHAR2(50 CHAR),
	FH_AUTORIZAGEST0OTRASFEC TIMESTAMP,
	TX_AUTORIZAJUNTA1ADMDOC VARCHAR2 (80 CHAR),
	TX_CONCEDIDAS1CONADMIN VARCHAR2 (80 CHAR),
	TX_SOLI1KMVIA VARCHAR2(20 CHAR),
	LG_CHECKDOC18 NUMBER(1) default 0,
	LG_CBDECLARO3 NUMBER(1) default 0,
	LG_CBDECLARO2 NUMBER(1) default 0,
	LG_CHECKDOC19 NUMBER(1) default 0,
	LG_CBDECLARO1 NUMBER(1) default 0,
	LG_CHECKDOC10 NUMBER(1) default 0,
	TX_TIPODESTINATARIO VARCHAR2(10 CHAR),
	LG_CHECKDOC11 NUMBER(1) default 0,
	LG_CHECKDOC12 NUMBER(1) default 0,
	LG_CHECKDOC13 NUMBER(1) default 0,
	LG_CHECKDOC14 NUMBER(1) default 0,
	LG_CHECKDOC15 NUMBER(1) default 0,
	LG_CHECKOTRA NUMBER(1) default 0,
	LG_CHECKDOC16 NUMBER(1) default 0,
	TX_AUTORIZAJUNTA0ADMPROC VARCHAR2 (80 CHAR),
	LG_CHECKDOC17 NUMBER(1) default 0,
	FH_AUTOJUNTA0ADMFECHA TIMESTAMP,
	TX_AUTORIZAGEST0OTRASPRO VARCHAR2 (80 CHAR),
	FH_CONCEDIDAS0FECHA TIMESTAMP,
	TX_CALIDADDE VARCHAR2(50 CHAR),
	NU_CONCEDIDAS0CONIMPORTE NUMBER (20, 2),
	TX_CONCEDIDAS1MINIMIS VARCHAR2 (50 CHAR),
	TX_REPETAGRUP0SIGLAS VARCHAR2 (20 CHAR),
	TX_SOLI1NOMBRE VARCHAR2 (150 CHAR),
	TX_REPR1NUMIDENT VARCHAR2 (20 CHAR),
	TX_SOLI1TIPOVIA VARCHAR2 (20 CHAR),
	LG_CHECKTIPO2 NUMBER (1) default 0,
	LG_CHECKFINALIDAD3 NUMBER (1) default 0,
	LG_CHECKTIPO1 NUMBER (1) default 0,
	LG_CHECKFINALIDAD4 NUMBER (1) default 0,
	LG_CHECKFINALIDAD1 NUMBER (1) default 0,
	LG_CHECKFINALIDAD2 NUMBER (1) default 0,
	TX_SOLI1BLOQUE VARCHAR2 (50 CHAR),
	TX_REPET2AGRUPIDENTIF VARCHAR2 (20 CHAR),
	NU_REPR1CODMUNICIPIO VARCHAR2 (10 CHAR),
	TX_SOL1LETRA VARCHAR2 (10 CHAR),
	TX_REPDATOS2EJECUCION VARCHAR2(20 CHAR),
	NU_CONCEDIDAS1CONIMPORTE NUMBER (20, 2),
	NU_SOLI1CODPROV NUMBER (3),
	TX_REPETAGRUP1NOMBRE VARCHAR2 (150 CHAR),
	NU_SOLICITADAS1IMPORTE NUMBER (20, 2),
	FH_SOLICITADAS1FECHA	TIMESTAMP,
	TX_SOLI1PUERTA VARCHAR2 (50 CHAR),
	TX_AUTORIZAGEST1OTRASADM VARCHAR2 (80 CHAR),
	TX_AUTORIZAJUNTA0ADMCONS VARCHAR2 (80 CHAR),
	TX_AUTORIZAJUNTA1ADMPROC VARCHAR2 (80 CHAR),
	LG_MEDIONOTIFTELEMATICA NUMBER (1) default 0,
	TX_SOLICITADAS1ADMIN VARCHAR2 (80 CHAR),
	TX_FIRM1LUGAR VARCHAR2 (50 CHAR),
	LG_CBDECLARO4 NUMBER (1) default 0,
	LG_CBDECLARO5 NUMBER (1) default 0,
	LG_CBDECLARO6 NUMBER (1) default 0,
	TX_REPR1APELLIDO1 VARCHAR2 (50 CHAR),
	TX_NOTIFNOMBRELUGAR VARCHAR2 (250 CHAR),
	TX_REPR1APELLIDO2 VARCHAR2 (50 CHAR),
	TX_AUTORIZAGEST0OTRASADM VARCHAR2 (80 CHAR),
	TX_FIRM1MES VARCHAR2(20 CHAR),
	LG_SOLI1MEDIONOTIFTELEMA NUMBER (1) default 0,
	NU_SOLI1TELEFONO NUMBER (9),
	TX_SOLI1TIPOIDENT VARCHAR2 (20 CHAR),
	LG_CHECKDOC21 NUMBER (1) default 0,
	CONV_NU_ID NUMBER(19),
	VB_TECNICO NUMBER(1,0)  default 0,
	VB_COORDINADOR NUMBER(1,0)  default 0,
	DESCRIPCION VARCHAR2 (4000 CHAR),
	MUNICIPIO VARCHAR2 (4000 CHAR),
	FH_INICIO DATE,
	FK_PAIS VARCHAR2(72 CHAR),
	PLAZO NUMBER(8, 0),
	FH_PAGO_SUBVENCION DATE,
	FH_PRESENTACION DATE,
	LG_REPRESENTACION NUMBER (1) default 0,
	FH_REGISTRO DATE,
	TX_LUGAR_REGISTRO VARCHAR2 (50 CHAR),
    TX_RESP_APELLIDOS VARCHAR2 (50 CHAR),
    TX_RESP_NOMBRE VARCHAR2 (50 CHAR),
    TX_RESP_NIF VARCHAR2 (50 CHAR)
	)
	TABLESPACE "&TABLESPACE_DATOS" LOGGING;


	COMMENT ON TABLE AACI_T_SOLICITUDSUBONGD IS 'Tabla de solicitudes para subvenciones a ONGD';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.ID_SOLICITUD IS 'Identificador único de la solicitud';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.NU_NUMEXPEDIENTE IS 'Número de expediente';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_PERSONANOTIF IS 'TX_PERSONANOTIF';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_REPETAGRUP1RACDA IS 'TX_REPETAGRUP1RACDA';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_SOLI1MEDNOTIFORD IS 'TX_SOLI1MEDNOTIFORD';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_REPETAGRUP2SIGLAS IS 'TX_REPETAGRUP2SIGLAS';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_SOLI1APELLIDO1 IS 'TX_SOLI1APELLIDO1';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_REPR1NOMBRE IS 'TX_REPR1NOMBRE';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_SOLI1APELLIDO2 IS 'TX_SOLI1APELLIDO2';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_AGRUPREPNOMBRE IS 'TX_AGRUPREPNOMBRE';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.FH_AUTORIZAGEST1OTRASFEC IS 'FH_AUTORIZAGEST1OTRASFEC';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_AUTORIZAGEST1OTRASDOC IS 'TX_AUTORIZAGEST1OTRASDOC';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_SOLI1PISO IS 'TX_SOLI1PISO';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_FIRM1ANO IS 'TX_FIRM1ANO';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_REPDATOS1EJECUCION IS 'TX_REPDATOS1EJECUCION';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_NOTIFTELEFONOAUTLUGAR IS 'TX_NOTIFTELEFONOAUTLUGAR';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_AUTORIZAGEST1OTRASPRO IS 'TX_AUTORIZAGEST1OTRASPRO';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.NU_SOLICITADASOLIMPORTE IS 'NU_SOLICITADASOLIMPORTE';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CHECKDOC1 IS 'LG_CHECKDOC1';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_REPR1SEXO IS 'TX_REPR1SEXO';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_SOLI1SIGLAS IS 'TX_SOLI1SIGLAS';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CHECKDOC2 IS 'LG_CHECKDOC2';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_CONCEDIDASCONADMIN IS 'TX_CONCEDIDASCONADMIN';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CHECKDOC3 IS 'LG_CHECKDOC3';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.NU_FIRM1IMPORTE IS 'NU_FIRM1IMPORTE';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CHECKDOC4 IS 'LG_CHECKDOC4';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CHECKDOC5 IS 'LG_CHECKDOC5';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CHECKDOC6 IS 'LG_CHECKDOC6';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CHECKDOC7 IS 'LG_CHECKDOC7';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CHECKDOC8 IS 'LG_CHECKDOC8';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_NOTIFNUMIDENTLUGAR IS 'TX_NOTIFNUMIDENTLUGAR';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CHECKDOC9 IS 'LG_CHECKDOC9';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_REPETAGRUPRACDA IS 'TX_REPETAGRUPRACDA';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_SOLI1ALTANOTIFICA IS 'LG_SOLI1ALTANOTIFICA';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_REPETAGRUP2RACDA IS 'TX_REPETAGRUP2RACDA';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_SOLI1NUMIDENT IS 'TX_SOLI1NUMIDENT';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_FIRM1FDO IS 'TX_FIRM1FDO';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.FH_AUTOJUNTA1ADMFECHA IS 'FH_AUTOJUNTA1ADMFECHA';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_SOLICITADAS0ADMIN IS 'TX_SOLICITADAS0ADMIN';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_AUTORIZAGEST0OTRASDOC IS 'TX_AUTORIZAGEST0OTRASDOC';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_AUTORIZAJUNTA0ADMDOC IS 'TX_AUTORIZAJUNTA0ADMDOC';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_AGRUPREPAPELLIDO2 IS 'TX_AGRUPREPAPELLIDO2';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_AGRUPREPAPELLIDO1 IS 'TX_AGRUPREPAPELLIDO1';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_REPETAGRUPNOMBRE IS 'TX_REPETAGRUPNOMBRE';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_SOLICITADAS1MINIMIS IS 'TX_SOLICITADAS1MINIMIS';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_AGRUPREPIDENTIFIC IS 'TX_AGRUPREPIDENTIFIC';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_FIRM1DIA IS 'TX_FIRM1DIA';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_SOLICITADAS0FECHA IS 'TX_SOLICITADAS0FECHA';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_REPR1TIPOVIA IS 'TX_REPR1TIPOVIA';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_SOLI1EMAIL IS 'TX_SOLI1EMAIL';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_SOLI1NUMERO IS 'TX_SOLI1NUMERO';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_DATOSTITULO IS 'TX_DATOSTITULO';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_CONCEDIDAS0MINIMIS IS 'TX_CONCEDIDAS0MINIMIS';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_REPR1NOMBREVIA IS 'TX_REPR1NOMBREVIA';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_AUTORIZAJUNTA1ADMCONS IS 'TX_AUTORIZAJUNTA1ADMCONS';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_ERRORFINALIDADPROY IS 'TX_ERRORFINALIDADPROY';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_NOTIFEMAILAUTLUGAR IS 'TX_NOTIFEMAILAUTLUGAR';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_REPR1TIPOIDENT IS 'TX_REPR1TIPOIDENT';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_SOLICITADAS0MINIMIS IS 'TX_SOLICITADAS0MINIMIS';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.NU_SOLI1TLFMOVIL IS 'NU_SOLI1TLFMOVIL';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_REPR1TITULO IS 'TX_REPR1TITULO';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.NU_SOLI1CP IS 'NU_SOLI1CP';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_REPETAGRUP1IDENT IS 'TX_REPETAGRUP1IDENT';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.FH_CONCEDIDAS1FECHA IS 'FH_CONCEDIDAS1FECHA';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.NU_REPR1CODPROV IS 'NU_REPR1CODPROV';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_SOLI1POBLACION IS 'TX_SOLI1POBLACION';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LB_TEXTOOTRAAS IS 'LB_TEXTOOTRAAS';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_SOLI1NOMBREVIA IS 'TX_SOLI1NOMBREVIA';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_REPDATOS0EJECUCION IS 'TX_REPDATOS0EJECUCION';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_SOLI1ESCALERA IS 'TX_SOLI1ESCALERA';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_REPET0AGRUPIDENTIF IS 'TX_REPET0AGRUPIDENTIF';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_SOLI1SEXO IS 'TX_SOLI1SEXO';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CHECKDOC20 IS 'LG_CHECKDOC20';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_SOLI1PORTAL IS 'TX_SOLI1PORTAL';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CONSENTEXPRESOREPR IS 'LG_CONSENTEXPRESOREPR';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_SOLI1CODIGO IS 'TX_SOLI1CODIGO';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.FH_AUTORIZAGEST0OTRASFEC IS 'FH_AUTORIZAGEST0OTRASFEC';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_AUTORIZAJUNTA1ADMDOC IS 'TX_AUTORIZAJUNTA1ADMDOC';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_CONCEDIDAS1CONADMIN IS 'TX_CONCEDIDAS1CONADMIN';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_SOLI1KMVIA IS 'TX_SOLI1KMVIA';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CHECKDOC18 IS 'LG_CHECKDOC18';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CBDECLARO3 IS 'LG_CBDECLARO3';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CBDECLARO2 IS 'LG_CBDECLARO2';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CHECKDOC19 IS 'LG_CHECKDOC19';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CBDECLARO1 IS 'LG_CBDECLARO1';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CHECKDOC10 IS 'LG_CHECKDOC10';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_TIPODESTINATARIO IS 'TX_TIPODESTINATARIO';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CHECKDOC11 IS 'LG_CHECKDOC11';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CHECKDOC12 IS 'LG_CHECKDOC12';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CHECKDOC13 IS 'LG_CHECKDOC13';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CHECKDOC14 IS 'LG_CHECKDOC14';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CHECKDOC15 IS 'LG_CHECKDOC15';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CHECKOTRA IS 'LG_CHECKOTRA';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CHECKDOC16 IS 'LG_CHECKDOC16';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_AUTORIZAJUNTA0ADMPROC IS 'TX_AUTORIZAJUNTA0ADMPROC';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CHECKDOC17 IS 'LG_CHECKDOC17';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.FH_AUTOJUNTA0ADMFECHA IS 'FH_AUTOJUNTA0ADMFECHA';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_AUTORIZAGEST0OTRASPRO IS 'TX_AUTORIZAGEST0OTRASPRO';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.FH_CONCEDIDAS0FECHA IS 'FH_CONCEDIDAS0FECHA';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_CALIDADDE IS 'TX_CALIDADDE';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.NU_CONCEDIDAS0CONIMPORTE IS 'NU_CONCEDIDAS0CONIMPORTE';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_CONCEDIDAS1MINIMIS IS 'TX_CONCEDIDAS1MINIMIS';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_REPETAGRUP0SIGLAS IS 'TX_REPETAGRUP0SIGLAS';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_SOLI1NOMBRE IS 'TX_SOLI1NOMBRE';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_REPR1NUMIDENT IS 'TX_REPR1NUMIDENT';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_SOLI1TIPOVIA IS 'TX_SOLI1TIPOVIA';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CHECKTIPO2 IS 'LG_CHECKTIPO2';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CHECKFINALIDAD3 IS 'LG_CHECKFINALIDAD3';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CHECKTIPO1 IS 'LG_CHECKTIPO1';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CHECKFINALIDAD4 IS 'LG_CHECKFINALIDAD4';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CHECKFINALIDAD1 IS 'LG_CHECKFINALIDAD1';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CHECKFINALIDAD2 IS 'LG_CHECKFINALIDAD2';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_SOLI1BLOQUE IS 'TX_SOLI1BLOQUE';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_REPET2AGRUPIDENTIF IS 'TX_REPET2AGRUPIDENTIF';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.NU_REPR1CODMUNICIPIO IS 'NU_REPR1CODMUNICIPIO';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_SOL1LETRA IS 'TX_SOL1LETRA';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_REPDATOS2EJECUCION IS 'TX_REPDATOS2EJECUCION';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.NU_CONCEDIDAS1CONIMPORTE IS 'NU_CONCEDIDAS1CONIMPORTE';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.NU_SOLI1CODPROV IS 'NU_SOLI1CODPROV';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_REPETAGRUP1NOMBRE IS 'TX_REPETAGRUP1NOMBRE';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.NU_SOLICITADAS1IMPORTE IS 'NU_SOLICITADAS1IMPORTE';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.FH_SOLICITADAS1FECHA IS 'FH_SOLICITADAS1FECHA';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_SOLI1PUERTA IS 'TX_SOLI1PUERTA';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_AUTORIZAGEST1OTRASADM IS 'TX_AUTORIZAGEST1OTRASADM';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_AUTORIZAJUNTA0ADMCONS IS 'TX_AUTORIZAJUNTA0ADMCONS';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_AUTORIZAJUNTA1ADMPROC IS 'TX_AUTORIZAJUNTA1ADMPROC';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_MEDIONOTIFTELEMATICA IS 'LG_MEDIONOTIFTELEMATICA';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_SOLICITADAS1ADMIN IS 'TX_SOLICITADAS1ADMIN';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_FIRM1LUGAR IS 'TX_FIRM1LUGAR';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CBDECLARO4 IS 'LG_CBDECLARO4';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CBDECLARO5 IS 'LG_CBDECLARO5';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CBDECLARO6 IS 'LG_CBDECLARO6';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_REPR1APELLIDO1 IS 'TX_REPR1APELLIDO1';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_NOTIFNOMBRELUGAR IS 'TX_NOTIFNOMBRELUGAR';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_REPR1APELLIDO2 IS 'TX_REPR1APELLIDO2';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_AUTORIZAGEST0OTRASADM IS 'TX_AUTORIZAGEST0OTRASADM';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_FIRM1MES IS 'TX_FIRM1MES';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_SOLI1MEDIONOTIFTELEMA IS 'LG_SOLI1MEDIONOTIFTELEMA';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.NU_SOLI1TELEFONO IS 'NU_SOLI1TELEFONO';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.TX_SOLI1TIPOIDENT IS 'TX_SOLI1TIPOIDENT';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.LG_CHECKDOC21 IS 'LG_CHECKDOC21';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.VB_TECNICO IS 'Bandera para el visto bueno del técnico';
	COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.VB_COORDINADOR IS 'Bandera para el visto bueno del coordinador';
    COMMENT ON COLUMN AACI_T_SOLICITUDSUBONGD.DESCRIPCION IS 'Descripción de la solicitud';


    CREATE TABLE "&USUARIO".AACI_T_TIPO_CONV (
    TCONV_NU_ID        NUMBER(19,0) NOT NULL,
    TCONV_LI_DENOMINACION   VARCHAR2(56 BYTE)
	)
    TABLESPACE "&TABLESPACE_DATOS";

	COMMENT ON COLUMN AACI_T_TIPO_CONV.TCONV_NU_ID IS 'Identificación del tipo convocatoria';
    COMMENT ON COLUMN AACI_T_TIPO_CONV.TCONV_LI_DENOMINACION IS 'Denominación del tipo de la convocatoria';


    CREATE TABLE "&USUARIO".AACI_T_CONVOCATORIAS (
    CONV_NU_ID NUMBER(19,0), 
    CONV_X_EXPE NUMBER (19,0),
	TCONV_NU_ID NUMBER(19,0),
	CONV_LI_ABREV_PROCEDIMIENTO NUMBER(10,0),
	CONV_LI_TITULO VARCHAR2(1000 BYTE),
	CONV_LI_DESCRIPCION VARCHAR2(4000 BYTE), 
	CONV_NU_ANIO NUMBER(4,0),
	CONV_FH_INICIO DATE, 
	CONV_FH_FIN DATE, 
	CONV_FH_VALORACION DATE, 
	CONV_FH_PROP_RESOL_PROV DATE, 
	CONV_FH_LIMIT_DOC_RESOL_DEF DATE,
	CONV_FH_RESOL_CONCE DATE
	)
	TABLESPACE "&TABLESPACE_DATOS";

	COMMENT ON COLUMN AACI_T_CONVOCATORIAS.CONV_NU_ID                   IS'Identificador del tipo convocatoria';
	COMMENT ON COLUMN AACI_T_CONVOCATORIAS.CONV_X_EXPE                  IS'Identificador del expediente en trewa';
	COMMENT ON COLUMN AACI_T_CONVOCATORIAS.CONV_LI_ABREV_PROCEDIMIENTO  IS'Abreviatura del procedimiento';
	COMMENT ON COLUMN AACI_T_CONVOCATORIAS.CONV_LI_TITULO               IS'Titulo de la convocatoria';
	COMMENT ON COLUMN AACI_T_CONVOCATORIAS.CONV_LI_DESCRIPCION          IS'Descripción de la convocatoria';
	COMMENT ON COLUMN AACI_T_CONVOCATORIAS.CONV_NU_ANIO                 IS'Año de la convocatoria';
	COMMENT ON COLUMN AACI_T_CONVOCATORIAS.CONV_FH_INICIO               IS'Fecha inicio de la convocatoria';
	COMMENT ON COLUMN AACI_T_CONVOCATORIAS.CONV_FH_FIN                  IS'Fecha fin de la convocatoria';
	COMMENT ON COLUMN AACI_T_CONVOCATORIAS.CONV_FH_VALORACION           IS'Fecha para la valoración';
	COMMENT ON COLUMN AACI_T_CONVOCATORIAS.CONV_FH_PROP_RESOL_PROV      IS'Fecha para la propuesta de resolución provisional';
	COMMENT ON COLUMN AACI_T_CONVOCATORIAS.CONV_FH_LIMIT_DOC_RESOL_DEF  IS'Fecha limite para la documentación de la resolución definitiva';
	COMMENT ON COLUMN AACI_T_CONVOCATORIAS.CONV_FH_RESOL_CONCE          IS'Fecha  de la resolución de concesión';


    CREATE TABLE "&USUARIO".AACI_TIPO_CATALOGO (
    TCAT_NU_ID NUMBER(10,0),
    TCAT_CO_CODIGO varchar (10 CHAR),
    TCAT_LI_DESCRIPCION VARCHAR2(1000 BYTE),
    TCONV_NU_ID NUMBER(19,0),
    TCAT_NU_ANIO NUMBER(10,0),
    TCAT_LO_VALORADOR NUMBER(1,0) default 0,
    TCAT_LO_DOCUMENTACION NUMBER(1,0) default 0,
    TCAT_LO_COMUNICACION NUMBER(1,0) default 0
    )
    TABLESPACE "&TABLESPACE_DATOS";
    
	COMMENT ON COLUMN AACI_TIPO_CATALOGO.TCAT_NU_ID             IS 'Identificador del tipo catálogo';
	COMMENT ON COLUMN AACI_TIPO_CATALOGO.TCAT_CO_CODIGO         IS 'Código del tipo catálogo';
	COMMENT ON COLUMN AACI_TIPO_CATALOGO.TCAT_LI_DESCRIPCION    IS 'Descripción del tipo de catálogo';
	COMMENT ON COLUMN AACI_TIPO_CATALOGO.TCONV_NU_ID            IS 'Identificador del tipo de convocatoria';
	COMMENT ON COLUMN AACI_TIPO_CATALOGO.TCAT_NU_ANIO           IS 'Año del en el que esta activo';
	COMMENT ON COLUMN AACI_TIPO_CATALOGO.TCAT_LO_VALORADOR      IS 'Valorador que puede seleccionarlo';
	COMMENT ON COLUMN AACI_TIPO_CATALOGO.TCAT_LO_DOCUMENTACION  IS 'Bandera de documentación';
	COMMENT ON COLUMN AACI_TIPO_CATALOGO.TCAT_LO_COMUNICACION   IS 'Bandera de comunicación';
    

    CREATE TABLE "&USUARIO".AACI_CATALOGO (
    CAT_NU_ID  NUMBER(10,0),
    CAT_LI_DESCRIPCION VARCHAR2(1000 BYTE), 
    TCAT_NU_ID NUMBER(10,0), 
    CAT_LO_MOTIVO NUMBER(1,0) default 0, 
    CAT_LO_VALORADOR NUMBER(1,0) default 0, 
    CAT_CO_CODIGO VARCHAR2(10 CHAR)
    )
    TABLESPACE "&TABLESPACE_DATOS";
    
	COMMENT ON COLUMN AACI_CATALOGO.CAT_NU_ID           IS 'Identificador del catálogo';
	COMMENT ON COLUMN AACI_CATALOGO.CAT_LI_DESCRIPCION  IS 'Descripciín del catálogo';
	COMMENT ON COLUMN AACI_CATALOGO.TCAT_NU_ID          IS 'Fk al tipo de catálogo al que pertenece';
	COMMENT ON COLUMN AACI_CATALOGO.CAT_LO_MOTIVO       IS 'Año del en el que esta activo';
	COMMENT ON COLUMN AACI_CATALOGO.CAT_LO_VALORADOR    IS 'Bandera de documentación';
	COMMENT ON COLUMN AACI_CATALOGO.CAT_CO_CODIGO       IS 'Bandera de comunicación';
    

    CREATE TABLE "&usuario".AACI_SUBSANACION (
    SUB_NU_ID NUMBER(10,0), 
    SUB_FH_SUBSANACION DATE,
    SUB_FH_REGISTRO DATE,
    SUB_FH_ENTRADA DATE,
    SUB_FH_LIMITE DATE,
    SUB_FH_ENTREGA DATE,
    FK_SOLICITUD NUMBER(10,0), 
    SUB_LI_OBSERVACIONES VARCHAR2(4000 BYTE), 
    SUB_LI_MOTIVO_DESESTIMACION VARCHAR2(4000 CHAR),
    SUB_LI_LUGAR_REGISTRO VARCHAR2(4000 CHAR),
    SUB_LG_ALMERIA NUMBER(1, 0) default 0,
    SUB_LG_CADIZ NUMBER(1, 0) default 0,
    SUB_LG_CORDOBA NUMBER(1, 0) default 0,
    SUB_LG_GRANADA NUMBER(1, 0) default 0,
    SUB_LG_HUELVA NUMBER(1, 0) default 0,
    SUB_LG_JAEN NUMBER(1, 0) default 0,
    SUB_LG_MALAGA NUMBER(1, 0) default 0,
    SUB_LG_SEVILLA NUMBER(1, 0) default 0,
    SUB_LG_AFRICA NUMBER(1, 0) default 0,
    SUB_LG_PREV_RIESGOS NUMBER(1, 0) default 0,
    SUB_LG_SERVICIOS NUMBER(1, 0) default 0,
    SUB_LG_OTROS NUMBER(1, 0) default 0,
    SUB_LG_NO_ESPECIFICA NUMBER(1, 0) default 0
    )
    TABLESPACE "&TABLESPACE_DATOS";
    
	COMMENT ON COLUMN AACI_SUBSANACION.SUB_NU_ID                    IS 'Identificador de la subsanación';
	COMMENT ON COLUMN AACI_SUBSANACION.SUB_FH_SUBSANACION           IS 'fecha de la subsanación';
	COMMENT ON COLUMN AACI_SUBSANACION.FK_SOLICITUD                 IS 'Identificador de la solicitud a la que pertenece la subsanación';
	COMMENT ON COLUMN AACI_SUBSANACION.SUB_LI_OBSERVACIONES         IS 'Observaciones sobre la solicitud';
	COMMENT ON COLUMN AACI_SUBSANACION.SUB_LI_MOTIVO_DESESTIMACION  IS 'Motivo de desestimación';

    CREATE TABLE "&usuario".AACI_CATALOGO_SUBSANACION (
    CSUB_NU_ID NUMBER(10,0),
    CAT_NU_ID NUMBER(10,0), 
    SUB_NU_ID NUMBER(10,0), 
    MOTIVO VARCHAR2(4000 BYTE)
    )
    TABLESPACE "&TABLESPACE_DATOS";

	COMMENT ON COLUMN AACI_CATALOGO_SUBSANACION.CSUB_NU_ID IS 'Identificador de la subsanación';
	COMMENT ON COLUMN AACI_CATALOGO_SUBSANACION.CAT_NU_ID  IS 'fecha de la subsanación';
	COMMENT ON COLUMN AACI_CATALOGO_SUBSANACION.SUB_NU_ID  IS 'Identificador de la solicitud a la que pertenece la subsanación';
	COMMENT ON COLUMN AACI_CATALOGO_SUBSANACION.MOTIVO     IS 'Observaciones sobre la solicitud';


    CREATE TABLE "&USUARIO".AACI_TIPO_EXCLUSION (
    TEXC_NU_ID          NUMBER(10,0),
    TCONV_NU_ID         NUMBER(19,0),
    TEXC_NU_TIPO        NUMBER(19,0),
    TEXC_NU_ORDEN       NUMBER (10,0),
    TEXC_LI_DESCRIPCION VARCHAR2(1000 BYTE),
    TEXC_NU_ANIO        NUMBER(10,0)
    )
    TABLESPACE "&TABLESPACE_DATOS";

    COMMENT ON COLUMN AACI_TIPO_EXCLUSION.TEXC_NU_ID            IS 'Identificador del tipo exclusión';
    COMMENT ON COLUMN AACI_TIPO_EXCLUSION.TCONV_NU_ID           IS 'Identificador del tipo convocatoria';
    COMMENT ON COLUMN AACI_TIPO_EXCLUSION.TEXC_NU_ORDEN         IS 'Orden del tipo exclusión';
    COMMENT ON COLUMN AACI_TIPO_EXCLUSION.TEXC_LI_DESCRIPCION   IS 'Descripción del tipo de exclusión';
    COMMENT ON COLUMN AACI_TIPO_EXCLUSION.TEXC_NU_ANIO          IS 'Año activación tipo exclusión';
    
    
    CREATE TABLE "&USUARIO".AACI_EXCLUSION (
    EXCL_NU_ID              NUMBER(19,0),
    TEXC_NU_ID              NUMBER(19,0),
    EXCL_LI_DESCRIPCION     VARCHAR2(1000 BYTE),
    EXCL_LI_PERFIL          VARCHAR2(50 BYTE),
    EXCL_NU_ORDEN          NUMBER(10,0),
    EXCL_NU_ANIO            NUMBER(4,0)
    )
    TABLESPACE "&TABLESPACE_DATOS";
    
    COMMENT ON COLUMN AACI_EXCLUSION.EXCL_NU_ID             IS 'Identificador de la exclusión';
    COMMENT ON COLUMN AACI_EXCLUSION.TEXC_NU_ID             IS 'Identificador del tipo de exclusión';
    COMMENT ON COLUMN AACI_EXCLUSION.EXCL_LI_DESCRIPCION    IS 'Descripción de la exclusión';
    COMMENT ON COLUMN AACI_EXCLUSION.EXCL_LI_PERFIL         IS 'Perfiles que podrán ver este tipo exclusión';
    COMMENT ON COLUMN AACI_EXCLUSION.EXCL_NU_ORDEN          IS 'Orden del tipo exclusión';
    COMMENT ON COLUMN AACI_EXCLUSION.EXCL_NU_ANIO           IS 'Año activación exclusión';
    
    CREATE TABLE "&USUARIO".AACI_EXCLUSIONES_SOLICITUD (
    EXCL_NU_ID  NUMBER(19,0),
    SOLI_NU_ID  NUMBER(19,0)
    )
    TABLESPACE "&TABLESPACE_DATOS";
    
    COMMENT ON COLUMN AACI_EXCLUSIONES_SOLICITUD.EXCL_NU_ID             IS 'Identificador de la exclusión';
    COMMENT ON COLUMN AACI_EXCLUSIONES_SOLICITUD.SOLI_NU_ID             IS 'Identificador de la solicitud';
    
    CREATE TABLE "&usuario".AACI_T_HISTORICO (
    HIS_NU_ID NUMBER(19,0),
    HIS_X_EXPE VARCHAR2(150 CHAR), 
    HIS_FEC DATE, 
    HIS_USU VARCHAR2(150 CHAR)
    )
    TABLESPACE "&TABLESPACE_DATOS";

	COMMENT ON COLUMN AACI_T_HISTORICO.HIS_NU_ID IS 'Identificador del histórico';
	COMMENT ON COLUMN AACI_T_HISTORICO.HIS_X_EXPE  IS 'Número de expediente';
	COMMENT ON COLUMN AACI_T_HISTORICO.HIS_FEC IS 'Fecha de alta del histórico';
	COMMENT ON COLUMN AACI_T_HISTORICO.HIS_USU IS 'Usuario de la aplicación';
	
    
SPOOL OFF