SPOOL 02_AACI_secuencias.log

DEF USUARIO= AACID_OWNER;

CREATE SEQUENCE "&USUARIO".AACI_SEQ_SOLIONGD INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE "&USUARIO".AACI_SEQ_CONV INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE "&USUARIO".AACI_SEQ_TIPO_CONV INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE "&USUARIO".AACI_SEQ_TIPO_CATALOGO INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE "&USUARIO".AACI_SEQ_CATALOGO INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE "&USUARIO".AACI_SEQ_SUBSANACION INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE "&USUARIO".AACI_SEQ_CATALOGO_SUBSANACION INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE "&USUARIO".AACI_SEQ_TIPO_EXCLUSION INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE "&USUARIO".AACI_SEQ_EXCLUSION INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE "&USUARIO".AACI_SEQ_HISTORICO INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE NOORDER;

SPOOL OFF