SPOOL 05_AACI_constraints.log

DEF USUARIO=AACID_OWNER;
DEF TABLESPACE_INDICES=TS_I_AACID_OWNER;

ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD CONSTRAINT AACI_IDSOLIC_PK PRIMARY KEY ( ID_SOLICITUD ) USING INDEX TABLESPACE "&TABLESPACE_INDICES";
ALTER TABLE "&USUARIO".AACI_T_TIPO_CONV ADD CONSTRAINT AACI_T_TIPO_CONV_PK PRIMARY KEY ( TCONV_NU_ID ) USING INDEX TABLESPACE "&TABLESPACE_INDICES";
ALTER TABLE "&USUARIO".AACI_T_CONVOCATORIAS ADD CONSTRAINT AACI_T_CONVOCATORIAS_PK PRIMARY KEY (CONV_NU_ID) USING INDEX TABLESPACE "&TABLESPACE_INDICES";
ALTER TABLE "&USUARIO".AACI_TIPO_CATALOGO ADD CONSTRAINT AACI_TIPO_CATALOGO_PK PRIMARY KEY (TCAT_NU_ID) USING INDEX TABLESPACE "&TABLESPACE_INDICES";
ALTER TABLE "&USUARIO".AACI_CATALOGO ADD CONSTRAINT AACI_CATALOGO_PK PRIMARY KEY (CAT_NU_ID) USING INDEX TABLESPACE "&TABLESPACE_INDICES";
ALTER TABLE "&USUARIO".AACI_SUBSANACION ADD CONSTRAINT AACI_SUBSANACION_PK PRIMARY KEY (SUB_NU_ID) USING INDEX TABLESPACE "&TABLESPACE_INDICES";
ALTER TABLE "&USUARIO".AACI_CATALOGO_SUBSANACION ADD CONSTRAINT AACI_CATALOGO_SUBSANACION_PK PRIMARY KEY (CSUB_NU_ID) USING INDEX TABLESPACE "&TABLESPACE_INDICES";
ALTER TABLE "&USUARIO".AACI_TIPO_EXCLUSION ADD CONSTRAINT AACI_TIPO_EXCLUSION_PK PRIMARY KEY (TEXC_NU_ID) USING INDEX TABLESPACE "&TABLESPACE_INDICES";
ALTER TABLE "&USUARIO".AACI_EXCLUSION ADD CONSTRAINT AACI_EXCLUSION_PK PRIMARY KEY ( EXCL_NU_ID ) USING INDEX TABLESPACE "&TABLESPACE_INDICES";


ALTER TABLE "&USUARIO".AACI_TIPO_CATALOGO ADD CONSTRAINT FK_AACI_TIPO_CATAL_TIPO_CONV FOREIGN KEY ( TCONV_NU_ID ) REFERENCES "&USUARIO".AACI_T_TIPO_CONV ( TCONV_NU_ID ) ;
ALTER TABLE "&USUARIO".AACI_CATALOGO ADD CONSTRAINT FK_AACI_TIPO_CATALOGO_ID FOREIGN KEY ( TCAT_NU_ID ) REFERENCES "&USUARIO".AACI_TIPO_CATALOGO ( TCAT_NU_ID ) ;
ALTER TABLE "&USUARIO".AACI_SUBSANACION ADD CONSTRAINT FK_AACI_T_SOLICITUDSUBONGD_ID FOREIGN KEY ( FK_SOLICITUD ) REFERENCES "&USUARIO".AACI_T_SOLICITUDSUBONGD ( ID_SOLICITUD ) ;
ALTER TABLE "&USUARIO".AACI_CATALOGO_SUBSANACION ADD CONSTRAINT FK_AACI_CATALOGO_ID FOREIGN KEY ( CAT_NU_ID ) REFERENCES "&USUARIO".AACI_CATALOGO ( CAT_NU_ID ) ;
ALTER TABLE "&USUARIO".AACI_CATALOGO_SUBSANACION ADD CONSTRAINT FK_AACI_SUBSANACION_ID FOREIGN KEY ( SUB_NU_ID ) REFERENCES "&USUARIO".AACI_SUBSANACION ( SUB_NU_ID ) ;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD CONSTRAINT FK_AACI_CONVOCATORIA_ID FOREIGN KEY ( CONV_NU_ID ) REFERENCES "&USUARIO".AACI_T_CONVOCATORIAS ( CONV_NU_ID ) ;
ALTER TABLE "&USUARIO".AACI_TIPO_EXCLUSION ADD CONSTRAINT FK_AACI_TIPO_EXCL_TIPO_CONV FOREIGN KEY ( TCONV_NU_ID ) REFERENCES "&USUARIO".AACI_T_TIPO_CONV ( TCONV_NU_ID ) ;
ALTER TABLE "&USUARIO".AACI_EXCLUSION ADD CONSTRAINT FK_AACI_TIPO_EXCLUSION_ID FOREIGN KEY ( TEXC_NU_ID ) REFERENCES "&USUARIO".AACI_TIPO_EXCLUSION ( TEXC_NU_ID );
ALTER TABLE "&USUARIO".AACI_EXCLUSIONES_SOLICITUD ADD CONSTRAINT FK_AACI_EXCLUSIONES FOREIGN KEY ( EXCL_NU_ID ) REFERENCES "&USUARIO".AACI_EXCLUSION ( EXCL_NU_ID ) ;
ALTER TABLE "&USUARIO".AACI_EXCLUSIONES_SOLICITUD ADD CONSTRAINT FK_AACI_SOLICITUD FOREIGN KEY ( SOLI_NU_ID ) REFERENCES "&USUARIO".AACI_T_SOLICITUDSUBONGD ( ID_SOLICITUD );

ALTER TABLE "&USUARIO".AACI_T_HISTORICO ADD CONSTRAINT AACI_IDHIS_PK PRIMARY KEY ( HIS_NU_ID ) USING INDEX TABLESPACE "&TABLESPACE_INDICES";
			   
SPOOL OFF