SPOOL 06_ACCI_grants.log

DEF USUARIO_OWNER=AACID_OWNER;
DEF USUARIO_USER=AACID_USER;

GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_SOLIONGD TO "&USUARIO_USER";
GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_T_SOLICITUDSUBONGD TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_CONV TO "&USUARIO_USER";
GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_T_CONVOCATORIAS TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_TIPO_CONV TO "&USUARIO_USER";
GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_T_TIPO_CONV TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_TIPO_CATALOGO TO "&USUARIO_USER";
GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_TIPO_CATALOGO TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_CATALOGO TO "&USUARIO_USER";
GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_CATALOGO TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_SUBSANACION TO "&USUARIO_USER";
GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_SUBSANACION TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_CATALOGO_SUBSANACION TO "&USUARIO_USER";
GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_CATALOGO_SUBSANACION TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_TIPO_EXCLUSION TO "&USUARIO_USER";
GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_TIPO_EXCLUSION TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_EXCLUSION TO "&USUARIO_USER";
GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_EXCLUSION TO "&USUARIO_USER";
GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_EXCLUSIONES_SOLICITUD TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_HISTORICO TO "&USUARIO_USER";
GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_T_HISTORICO TO "&USUARIO_USER";

SPOOL OFF