SPOOL 08_ACCI_sinonimos.log

DEF USUARIO_OWNER=AACID_OWNER;
DEF USUARIO_USER=AACID_USER;

CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_SOLIONGD FOR "&USUARIO_OWNER".AACI_SEQ_SOLIONGD;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_T_SOLICITUDSUBONGD FOR "&USUARIO_OWNER".AACI_T_SOLICITUDSUBONGD;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_CONV FOR "&USUARIO_OWNER".AACI_SEQ_CONV;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_T_CONVOCATORIAS FOR "&USUARIO_OWNER".AACI_T_CONVOCATORIAS;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_TIPO_CONV FOR "&USUARIO_OWNER".AACI_SEQ_TIPO_CONV;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_T_TIPO_CONV FOR "&USUARIO_OWNER".AACI_T_TIPO_CONV;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_TIPO_CATALOGO FOR "&USUARIO_OWNER".AACI_SEQ_TIPO_CATALOGO;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_TIPO_CATALOGO FOR "&USUARIO_OWNER".AACI_TIPO_CATALOGO;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_CATALOGO FOR "&USUARIO_OWNER".AACI_SEQ_CATALOGO;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_CATALOGO FOR "&USUARIO_OWNER".AACI_CATALOGO;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_SUBSANACION FOR "&USUARIO_OWNER".AACI_SEQ_SUBSANACION;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SUBSANACION FOR "&USUARIO_OWNER".AACI_SUBSANACION;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_CATALOGO_SUBSANACION FOR "&USUARIO_OWNER".AACI_SEQ_CATALOGO_SUBSANACION;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_CATALOGO_SUBSANACION FOR "&USUARIO_OWNER".AACI_CATALOGO_SUBSANACION;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_TIPO_EXCLUSION FOR "&USUARIO_OWNER".AACI_SEQ_TIPO_EXCLUSION;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_TIPO_EXCLUSION FOR "&USUARIO_OWNER".AACI_TIPO_EXCLUSION;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_EXCLUSION FOR "&USUARIO_OWNER".AACI_SEQ_EXCLUSION;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_EXCLUSION FOR "&USUARIO_OWNER".AACI_EXCLUSION;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_EXCLUSIONES_SOLICITUD FOR "&USUARIO_OWNER".AACI_EXCLUSIONES_SOLICITUD;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_HISTORICO FOR "&USUARIO_OWNER".AACI_SEQ_HISTORICO;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_T_HISTORICO FOR "&USUARIO_OWNER".AACI_T_HISTORICO;

SPOOL OFF