SPOOL OWNER_AACID_UPDATE_FINALIDAD.log

DEF USUARIO=AACID_OWNER;

UPDATE "&USUARIO".AACI_FINALIDAD SET FINA_CO_CODIGO = 'INN' WHERE FINA_CO_CODIGO ='IU';
UPDATE "&USUARIO".AACI_FINALIDAD SET FINA_CO_CODIGO = 'EDD' WHERE FINA_CO_CODIGO ='EU';
UPDATE "&USUARIO".AACI_FINALIDAD SET FINA_CO_CODIGO = 'FE' WHERE FINA_CO_CODIGO ='FU';

commit;

SPOOL OFF