SPOOL 06_AACID_OWNER_AACI_grants.log

DEF USUARIO_OWNER=AACID_OWNER;
DEF USUARIO_USER=AACID_USER;

GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_T_CRITERIOS TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_T_CRITERIOS TO "&USUARIO_USER";

GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_CRITERIOS TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_CRITERIOS TO "&USUARIO_USER";

GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_SOLICITUD_CRITERIO TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_SOLICITUD_CRITERIO TO "&USUARIO_USER";

GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_SOLICITUDES_AUXILIAR TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_SOLICITUDES_AUXILIAR TO "&USUARIO_USER";

GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_FINALIDAD TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_FINALIDAD TO "&USUARIO_USER";

GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_GASTOS_FINALIDAD TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_GASTOS_FINALIDAD TO "&USUARIO_USER";

GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_GASTOS TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_GASTOS TO "&USUARIO_USER";

GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_FUNCIONES TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_FUNCIONES TO "&USUARIO_USER";

GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_T_ENTIDAD_PARTICIPANTE TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_T_ENT_PARTICIPANTE TO "&USUARIO_USER";

GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_ENTIDADES_PARTICIPANTES TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_ENT_PARTICIPANTES TO "&USUARIO_USER";

GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_SOLICITUD_TCRITERIO TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_SOLI_TCRITERIO TO "&USUARIO_USER";

GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_TM_CAPACIDAD_GESTION TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_CAPACIDAD_GESTION TO "&USUARIO_USER";

GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_PAISES TO "&USUARIO_USER";
GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_T_PAISES TO "&USUARIO_USER";

GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_T_PAISES_SOLICITUD TO "&USUARIO_USER";


SPOOL OFF