SPOOL 08_AACID_USER_AACI_sinonimos.log

DEF USUARIO_OWNER=AACID_OWNER;
DEF USUARIO_USER=AACID_USER;


CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_T_CRITERIOS FOR "&USUARIO_OWNER".AACI_SEQ_T_CRITERIOS;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_T_CRITERIOS FOR "&USUARIO_OWNER".AACI_T_CRITERIOS;

CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_CRITERIOS FOR "&USUARIO_OWNER".AACI_SEQ_CRITERIOS;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_CRITERIOS FOR "&USUARIO_OWNER".AACI_CRITERIOS;	

CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_SOLICITUD_CRITERIO FOR "&USUARIO_OWNER".AACI_SEQ_SOLICITUD_CRITERIO;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SOLICITUD_CRITERIO FOR "&USUARIO_OWNER".AACI_SOLICITUD_CRITERIO;	

CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_SOLICITUDES_AUXILIAR FOR "&USUARIO_OWNER".AACI_SEQ_SOLICITUDES_AUXILIAR;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SOLICITUDES_AUXILIAR FOR "&USUARIO_OWNER".AACI_SOLICITUDES_AUXILIAR;

CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_FINALIDAD FOR "&USUARIO_OWNER".AACI_SEQ_FINALIDAD;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_FINALIDAD FOR "&USUARIO_OWNER".AACI_FINALIDAD;

CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_GASTOS_FINALIDAD FOR "&USUARIO_OWNER".AACI_SEQ_GASTOS_FINALIDAD;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_GASTOS_FINALIDAD FOR "&USUARIO_OWNER".AACI_GASTOS_FINALIDAD;

CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_GASTOS FOR "&USUARIO_OWNER".AACI_SEQ_GASTOS;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_GASTOS FOR "&USUARIO_OWNER".AACI_GASTOS;

CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_FUNCIONES FOR "&USUARIO_OWNER".AACI_SEQ_FUNCIONES;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_FUNCIONES FOR "&USUARIO_OWNER".AACI_FUNCIONES;

CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_T_ENT_PARTICIPANTE FOR "&USUARIO_OWNER".AACI_SEQ_T_ENT_PARTICIPANTE;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_T_ENTIDAD_PARTICIPANTE FOR "&USUARIO_OWNER".AACI_T_ENTIDAD_PARTICIPANTE;

CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_ENT_PARTICIPANTES FOR "&USUARIO_OWNER".AACI_SEQ_ENT_PARTICIPANTES;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_ENTIDADES_PARTICIPANTES FOR "&USUARIO_OWNER".AACI_ENTIDADES_PARTICIPANTES;

CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_SOLI_TCRITERIO FOR "&USUARIO_OWNER".AACI_SEQ_SOLI_TCRITERIO;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SOLICITUD_TCRITERIO FOR "&USUARIO_OWNER".AACI_SOLICITUD_TCRITERIO;

CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_CAPACIDAD_GESTION FOR "&USUARIO_OWNER".AACI_SEQ_CAPACIDAD_GESTION;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_TM_CAPACIDAD_GESTION FOR "&USUARIO_OWNER".AACI_TM_CAPACIDAD_GESTION;

CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_PAISES FOR "&USUARIO_OWNER".AACI_SEQ_PAISES;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_T_PAISES FOR "&USUARIO_OWNER".AACI_T_PAISES;

CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_T_PAISES_SOLICITUD FOR "&USUARIO_OWNER".AACI_T_PAISES_SOLICITUD;

SPOOL OFF