SPOOL 03_ACCI_REVOKEs.log

DEF USUARIO_OWNER=AACID_OWNER;
DEF USUARIO_USER=AACID_USER;

REVOKE SELECT ON "&USUARIO_OWNER".AACI_SEQ_TEXCLU_SOLICITUD FROM "&USUARIO_USER";
REVOKE DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_TEXCLUSIONES_SOLICITUD FROM "&USUARIO_USER";

SPOOL OFF