SPOOL 04_AACID_OWNER_AACI_secuencias.log

DEF USUARIO= AACID_OWNER;

CREATE SEQUENCE "&USUARIO".AACI_SEQ_DOCUMENTO_EXPEDIENTE INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE "&USUARIO".AACI_SEQ_GASTOS INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE "&USUARIO".AACI_SEQ_GASTOS_FINALIDAD INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE "&USUARIO".AACI_SEQ_FUNCIONES INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE "&USUARIO".AACI_SEQ_T_ENT_PARTICIPANTE INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE NOORDER;

SPOOL OFF