SPOOL 06_AACID_OWNER_AACI_grants.log

DEF USUARIO_OWNER=AACID_OWNER;
DEF USUARIO_USER=AACID_USER;

GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_T_DOCUMENTO_EXPEDIENTE TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_DOCUMENTO_EXPEDIENTE TO "&USUARIO_USER";

GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_TM_ENTIDAD_CONTRAPARTE TO "&USUARIO_USER";

GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_GASTOS TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_GASTOS_FINALIDAD TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_FUNCIONES TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_T_ENT_PARTICIPANTE TO "&USUARIO_USER";

SPOOL OFF