SPOOL 02_AACI_secuencias.log

DEF USUARIO= AACID_OWNER;

CREATE SEQUENCE "&USUARIO".AACI_SEQ_AGRUPACIONES INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE "&USUARIO".AACI_SEQ_CONTRAPARTES INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE "&USUARIO".AACI_SEQ_CONTRIBUCIONES INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE "&USUARIO".AACI_SEQ_CON_CONTRAPARTE INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE "&USUARIO".AACI_SEQ_ENTIDAD_CONTRAPARTE INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE "&USUARIO".AACI_SEQ_CON_OTRAS INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE NOORDER;

SPOOL OFF