SPOOL 03_AACI_inserts.log

DEF USUARIO=AACID_OWNER;

Insert into "&USUARIO".AACI_EXCLUSION values ("&USUARIO".AACI_SEQ_EXCLUSION.NEXTVAL,(SELECT TEXC_NU_ID FROM "&USUARIO".AACI_TIPO_EXCLUSION WHERE TEXC_NU_ORDEN= 1 AND TEXC_NU_TIPO = 2 and TCONV_NU_ID = (SELECT TCONV_NU_ID FROM "&USUARIO".AACI_T_TIPO_CONV WHERE TCONV_LI_DENOMINACION = 'UNIV')),'No haber presentado la subsanación requerida (art. 22), siempre que lo solicitado se refiera a algún requisito exigido por la Orden reguladora.','DGA',95,2021);
Insert into "&USUARIO".AACI_EXCLUSION values ("&USUARIO".AACI_SEQ_EXCLUSION.NEXTVAL,(SELECT TEXC_NU_ID FROM "&USUARIO".AACI_TIPO_EXCLUSION WHERE TEXC_NU_ORDEN= 1 AND TEXC_NU_TIPO = 2 and TCONV_NU_ID = (SELECT TCONV_NU_ID FROM "&USUARIO".AACI_T_TIPO_CONV WHERE TCONV_LI_DENOMINACION = 'UNIV')),'Subsanación fuera de plazo (art. 22), siempre que lo presentado fuera de plazo se refiera a algún requisito exigido por la Orden reguladora.','DGA',96,2021);
Insert into "&USUARIO".AACI_EXCLUSION values ("&USUARIO".AACI_SEQ_EXCLUSION.NEXTVAL,(SELECT TEXC_NU_ID FROM "&USUARIO".AACI_TIPO_EXCLUSION WHERE TEXC_NU_ORDEN= 1 AND TEXC_NU_TIPO = 2 and TCONV_NU_ID = (SELECT TCONV_NU_ID FROM "&USUARIO".AACI_T_TIPO_CONV WHERE TCONV_LI_DENOMINACION = 'UNIV')),'Subsanación incompleta (art. 22), siempre que lo no presentado se refiera a algún requisito exigido por la Orden reguladora.','DGA',97,2021);
Insert into "&USUARIO".AACI_EXCLUSION values ("&USUARIO".AACI_SEQ_EXCLUSION.NEXTVAL,(SELECT TEXC_NU_ID FROM "&USUARIO".AACI_TIPO_EXCLUSION WHERE TEXC_NU_ORDEN= 1 AND TEXC_NU_TIPO = 2 and TCONV_NU_ID = (SELECT TCONV_NU_ID FROM "&USUARIO".AACI_T_TIPO_CONV WHERE TCONV_LI_DENOMINACION = 'UNIV')),'Desistimiento de la ONGD.','DGA',98,2021);
Insert into "&USUARIO".AACI_EXCLUSION values ("&USUARIO".AACI_SEQ_EXCLUSION.NEXTVAL,(SELECT TEXC_NU_ID FROM "&USUARIO".AACI_TIPO_EXCLUSION WHERE TEXC_NU_ORDEN= 1 AND TEXC_NU_TIPO = 2 and TCONV_NU_ID = (SELECT TCONV_NU_ID FROM "&USUARIO".AACI_T_TIPO_CONV WHERE TCONV_LI_DENOMINACION = 'UNIV')),'No aportar la documentación que acredite la concesión de financiación de las administraciones o instituciones públicas o privadas cofinanciadoras de la intervención distintas a las provenientes del país o países donde se vaya a desarrollar la intervención (art. 21).','VALORADOR,COORDINADOR',99,2021);
Insert into "&USUARIO".AACI_EXCLUSION values ("&USUARIO".AACI_SEQ_EXCLUSION.NEXTVAL,(SELECT TEXC_NU_ID FROM "&USUARIO".AACI_TIPO_EXCLUSION WHERE TEXC_NU_ORDEN= 1 AND TEXC_NU_TIPO = 2 and TCONV_NU_ID = (SELECT TCONV_NU_ID FROM "&USUARIO".AACI_T_TIPO_CONV WHERE TCONV_LI_DENOMINACION = 'UNIV')),'No aportar documentación acreditativa de la propiedad del terreno y su disponibilidad para que se realice la rehabilitación de inmuebles que contempla el proyecto (art. 21)','VALORADOR,COORDINADOR',100,2021);
Insert into "&USUARIO".AACI_EXCLUSION values ("&USUARIO".AACI_SEQ_EXCLUSION.NEXTVAL,(SELECT TEXC_NU_ID FROM "&USUARIO".AACI_TIPO_EXCLUSION WHERE TEXC_NU_ORDEN= 1 AND TEXC_NU_TIPO = 2 and TCONV_NU_ID = (SELECT TCONV_NU_ID FROM "&USUARIO".AACI_T_TIPO_CONV WHERE TCONV_LI_DENOMINACION = 'UNIV')),'No aportar certificado de disponibilidad de la autoridad en la zona, cuando la propietaria del terreno o inmueble fuera una administración pública o una entidad comunal (art. 21).','VALORADOR,COORDINADOR',101,2021);
Insert into "&USUARIO".AACI_EXCLUSION values ("&USUARIO".AACI_SEQ_EXCLUSION.NEXTVAL,(SELECT TEXC_NU_ID FROM "&USUARIO".AACI_TIPO_EXCLUSION WHERE TEXC_NU_ORDEN= 2 AND TEXC_NU_TIPO = 2 and TCONV_NU_ID = (SELECT TCONV_NU_ID FROM "&USUARIO".AACI_T_TIPO_CONV WHERE TCONV_LI_DENOMINACION = 'UNIV')),'No tener como contraparte a una o varias Universidades o centros de enseñanza superior, de carácter público, del país en el que se desarrolla el proyecto (art.3.1.b))','VALORADOR,COORDINADOR',102,2021);
Insert into "&USUARIO".AACI_EXCLUSION values ("&USUARIO".AACI_SEQ_EXCLUSION.NEXTVAL,(SELECT TEXC_NU_ID FROM "&USUARIO".AACI_TIPO_EXCLUSION WHERE TEXC_NU_ORDEN= 2 AND TEXC_NU_TIPO = 2 and TCONV_NU_ID = (SELECT TCONV_NU_ID FROM "&USUARIO".AACI_T_TIPO_CONV WHERE TCONV_LI_DENOMINACION = 'UNIV')),'No tener documento Marco de Colaboración suscrito con la entidad o entidades contrapartes del proyecto (art. 3.1.b))','VALORADOR,COORDINADOR',103,2021);
Insert into "&USUARIO".AACI_EXCLUSION values ("&USUARIO".AACI_SEQ_EXCLUSION.NEXTVAL,(SELECT TEXC_NU_ID FROM "&USUARIO".AACI_TIPO_EXCLUSION WHERE TEXC_NU_ORDEN= 3 AND TEXC_NU_TIPO = 2 and TCONV_NU_ID = (SELECT TCONV_NU_ID FROM "&USUARIO".AACI_T_TIPO_CONV WHERE TCONV_LI_DENOMINACION = 'UNIV')),'No acreditar tener como contraparte a entidad o entidades, sin ánimo de lucro, públicas o privadas,  legalmente constituidas y/o inscritas como entidades nacionales en los correspondientes Registros oficiales del país en el que se desarrolla el proyecto (art. 3.1.c) y art. 21)','VALORADOR,COORDINADOR',104,2021);
Insert into "&USUARIO".AACI_EXCLUSION values ("&USUARIO".AACI_SEQ_EXCLUSION.NEXTVAL,(SELECT TEXC_NU_ID FROM "&USUARIO".AACI_TIPO_EXCLUSION WHERE TEXC_NU_ORDEN= 3 AND TEXC_NU_TIPO = 2 and TCONV_NU_ID = (SELECT TCONV_NU_ID FROM "&USUARIO".AACI_T_TIPO_CONV WHERE TCONV_LI_DENOMINACION = 'UNIV')),'No presentar Convenio con el agente andaluz de cooperación, debidamente inscrito en el RACDA, con experiencia en la zona, que actúe como entidad colaboradora, donde se manifieste haber participado en la identificación y formulación del proyecto, así como sus responsabilidades específicas en la aplicación de la investigación o innovación (art. 3.1.c) y art. 21)','VALORADOR,COORDINADOR',105,2021);
Insert into "&USUARIO".AACI_EXCLUSION values ("&USUARIO".AACI_SEQ_EXCLUSION.NEXTVAL,(SELECT TEXC_NU_ID FROM "&USUARIO".AACI_TIPO_EXCLUSION WHERE TEXC_NU_ORDEN= 3 AND TEXC_NU_TIPO = 2 and TCONV_NU_ID = (SELECT TCONV_NU_ID FROM "&USUARIO".AACI_T_TIPO_CONV WHERE TCONV_LI_DENOMINACION = 'UNIV')),'No aportar documentación acreditativa del agente andaluz de cooperación con experiencia en la zona y en el sector de intervención, esto es, identificación del agente que va a participar, así como declaración jurada del representante del agente andaluz de las actividades desarrolladas en la zona (art. 3.1.c) y art. 21)','VALORADOR,COORDINADOR',106,2021);
Insert into "&USUARIO".AACI_EXCLUSION values ("&USUARIO".AACI_SEQ_EXCLUSION.NEXTVAL,(SELECT TEXC_NU_ID FROM "&USUARIO".AACI_TIPO_EXCLUSION WHERE TEXC_NU_ORDEN= 3 AND TEXC_NU_TIPO = 2 and TCONV_NU_ID = (SELECT TCONV_NU_ID FROM "&USUARIO".AACI_T_TIPO_CONV WHERE TCONV_LI_DENOMINACION = 'UNIV')),'No aportar documentación acreditativa de que la persona coordinadora del proyecto está en posesión del título de doctor (art. 3.1.c) y art. 21)','VALORADOR,COORDINADOR',107,2021);
Insert into "&USUARIO".AACI_EXCLUSION values ("&USUARIO".AACI_SEQ_EXCLUSION.NEXTVAL,(SELECT TEXC_NU_ID FROM "&USUARIO".AACI_TIPO_EXCLUSION WHERE TEXC_NU_ORDEN= 3 AND TEXC_NU_TIPO = 2 and TCONV_NU_ID = (SELECT TCONV_NU_ID FROM "&USUARIO".AACI_T_TIPO_CONV WHERE TCONV_LI_DENOMINACION = 'UNIV')),'No aportar documentación del grupo de investigación al que pertenece la persona coordinadora del proyecto (art. 3.1.c) y art. 21) ','VALORADOR,COORDINADOR',108,2021);
Insert into "&USUARIO".AACI_EXCLUSION values ("&USUARIO".AACI_SEQ_EXCLUSION.NEXTVAL,(SELECT TEXC_NU_ID FROM "&USUARIO".AACI_TIPO_EXCLUSION WHERE TEXC_NU_ORDEN= 3 AND TEXC_NU_TIPO = 2 and TCONV_NU_ID = (SELECT TCONV_NU_ID FROM "&USUARIO".AACI_T_TIPO_CONV WHERE TCONV_LI_DENOMINACION = 'UNIV')),'No aportar manifestación por escrito de la contraparte o contrapartes de haber participado en la identificación y formulación del proyecto, así como de sus responsabilidades específicas en su (art. 21','VALORADOR,COORDINADOR',109,2021);
commit;

SPOOL OFF