SPOOL 04_AACI_constraints.log

DEF USUARIO=AACID_OWNER;
DEF TABLESPACE_INDICES=TS_I_AACID_OWNER;

ALTER TABLE "&USUARIO".AACI_AGRUPACIONES ADD CONSTRAINT AACI_IDAGRUPACION_PK PRIMARY KEY ( AGRU_NU_ID ) USING INDEX TABLESPACE "&TABLESPACE_INDICES";
ALTER TABLE "&USUARIO".AACI_CONTRAPARTES ADD CONSTRAINT AACI_CONTRAPARTES_PK PRIMARY KEY ( CONT_NU_ID) USING INDEX TABLESPACE "&TABLESPACE_INDICES";
ALTER TABLE "&USUARIO".AACI_ENTIDAD_CONTRAPARTE ADD CONSTRAINT AACI_ENTIDAD_CONTRAPARTE_PK PRIMARY KEY (ENTI_NU_ID) USING INDEX TABLESPACE "&TABLESPACE_INDICES";
ALTER TABLE "&USUARIO".AACI_CONTRIBUCIONES ADD CONSTRAINT AACI_CONTRIBUCIONES_PK PRIMARY KEY (ID_CONTRIBUCION) USING INDEX TABLESPACE "&TABLESPACE_INDICES";
ALTER TABLE "&USUARIO".AACI_CON_CONTRAPARTE ADD CONSTRAINT AACI_CON_CONTRAPARTE_PK PRIMARY KEY (ID_CON_CONTRA) USING INDEX TABLESPACE "&TABLESPACE_INDICES";
ALTER TABLE "&USUARIO".AACI_CON_OTRAS ADD CONSTRAINT AACI_CON_OTRAS_PK PRIMARY KEY (ID_CON_OTRA) USING INDEX TABLESPACE "&TABLESPACE_INDICES";


ALTER TABLE "&USUARIO".AACI_AGRUPACIONES ADD CONSTRAINT FK_AACI_AGRUPACION_SOLICITUD FOREIGN KEY (ID_SOLICITUD) REFERENCES "&USUARIO".AACI_T_SOLICITUDSUBONGD (ID_SOLICITUD) ;
ALTER TABLE "&USUARIO".AACI_CONTRAPARTES ADD CONSTRAINT FK_AACI_CONTRAPARTE_SOLICITUD FOREIGN KEY (CONT_FK_SOLICITUD) REFERENCES "&USUARIO".AACI_T_SOLICITUDSUBONGD (ID_SOLICITUD) ;
ALTER TABLE "&USUARIO".AACI_CONTRAPARTES ADD CONSTRAINT FK_AACI_CONTRAPARTE_ENTIDAD FOREIGN KEY (ENTI_NU_ID) REFERENCES "&USUARIO".AACI_ENTIDAD_CONTRAPARTE ( ENTI_NU_ID ) ;
ALTER TABLE "&USUARIO".AACI_CON_CONTRAPARTE ADD CONSTRAINT FK_AACI_CON_CONTRIBUCIONES FOREIGN KEY (FK_CONTRIBUCION) REFERENCES "&USUARIO".AACI_CONTRIBUCIONES (ID_CONTRIBUCION) ;
ALTER TABLE "&USUARIO".AACI_CON_CONTRAPARTE ADD CONSTRAINT FK_AACI_CON_CONTRAPARTE FOREIGN KEY (FK_ENTIDAD) REFERENCES "&USUARIO".AACI_CONTRAPARTES (CONT_NU_ID) ;
ALTER TABLE "&USUARIO".AACI_CON_OTRAS ADD CONSTRAINT FK_AACI_CON_CONTRIBUCION FOREIGN KEY (FK_CONTRIBUCION) REFERENCES "&USUARIO".AACI_CONTRIBUCIONES (ID_CONTRIBUCION) ;
ALTER TABLE "&USUARIO".AACI_CON_OTRAS ADD CONSTRAINT FK_AACI_ENTIDAD FOREIGN KEY (FK_ENTIDAD) REFERENCES "&USUARIO".AACI_ENTIDAD_CONTRAPARTE (ENTI_NU_ID) ;

SPOOL OFF