SPOOL 06_ACCI_grants.log

DEF USUARIO_OWNER=AACID_OWNER;
DEF USUARIO_USER=AACID_USER;

GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_AGRUPACIONES TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_AGRUPACIONES TO "&USUARIO_USER";

GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_CONTRAPARTES TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_CONTRAPARTES TO "&USUARIO_USER";

GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_CON_CONTRAPARTE TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_CON_CONTRAPARTE TO "&USUARIO_USER";

GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_CON_OTRAS TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_CON_OTRAS TO "&USUARIO_USER";

GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_ENTIDAD_CONTRAPARTE TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_ENTIDAD_CONTRAPARTE TO "&USUARIO_USER";

GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_CONTRIBUCIONES TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_CONTRIBUCIONES TO "&USUARIO_USER";

SPOOL OFF