SPOOL 08_ACCI_sinonimos.log

DEF USUARIO_OWNER=AACID_OWNER;
DEF USUARIO_USER=AACID_USER;


CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_AGRUPACIONES FOR "&USUARIO_OWNER".AACI_SEQ_AGRUPACIONES;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_AGRUPACIONES FOR "&USUARIO_OWNER".AACI_T_AGRUPACIONES;

CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_CONTRAPARTES FOR "&USUARIO_OWNER".AACI_SEQ_CONTRAPARTES;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_CONTRAPARTES FOR "&USUARIO_OWNER".AACI_CONTRAPARTES;	

CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_CONTRIBUCIONES FOR "&USUARIO_OWNER".AACI_SEQ_CONTRIBUCIONES;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_CONTRIBUCIONES FOR "&USUARIO_OWNER".AACI_CONTRIBUCIONES;	

CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_CON_CONTRAPARTES FOR "&USUARIO_OWNER".AACI_SEQ_CONTRAPARTES;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_CON_CONTRAPARTES FOR "&USUARIO_OWNER".AACI_CONTRAPARTES;	

CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_CON_OTRAS FOR "&USUARIO_OWNER".AACI_SEQ_CON_OTRAS;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_CON_OTRAS FOR "&USUARIO_OWNER".AACI_CON_OTRAS;

CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_ENTIDAD_CONTRAPARTE FOR "&USUARIO_OWNER".AACI_ENTIDAD_CONTRAPARTE;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_T_ENTIDAD_CONTRAPARTE FOR "&USUARIO_OWNER".AACI_ENTIDAD_CONTRAPARTE;

SPOOL OFF