SPOOL 04_AACID_OWNER_tablas_rollback.log

DEF USUARIO=AACID_OWNER;

--Procesamiento Específico Alegaciones/Aceptación/Reformulación--

ALTER TABLE "&USUARIO".AACI_SOLICITUDES_AUXILIAR DROP COLUMN "SOAU_NU_PUNTUACION_TOTAL";

ALTER TABLE "&USUARIO".AACI_CRITERIOS DROP COLUMN "CRIT_NU_ORDEN";

SPOOL OFF