SPOOL 02_AACID_OWNER_AACI_secuencias_rollback.log

DEF USUARIO=AACID_OWNER;

DROP SEQUENCE "&USUARIO".AACI_SEQ_T_CRITERIOS;
DROP SEQUENCE "&USUARIO".AACI_SEQ_CRITERIOS;
DROP SEQUENCE "&USUARIO".AACI_SEQ_SOLICITUD_CRITERIO;
DROP SEQUENCE "&USUARIO".AACI_SEQ_SOLICITUDES_AUXILIAR;
DROP SEQUENCE "&USUARIO".AACI_SEQ_FINALIDAD;
DROP SEQUENCE "&USUARIO".AACI_SEQ_GASTOS_FINALIDAD;
DROP SEQUENCE "&USUARIO".AACI_SEQ_GASTOS;
DROP SEQUENCE "&USUARIO".AACI_SEQ_FUNCIONES;
DROP SEQUENCE "&USUARIO".AACI_SEQ_T_ENT_PARTICIPANTE;
DROP SEQUENCE "&USUARIO".AACI_SEQ_ENT_PARTICIPANTES;
DROP SEQUENCE "&USUARIO".AACI_SEQ_SOLI_TCRITERIO;
DROP SEQUENCE "&USUARIO".AACI_SEQ_CAPACIDAD_GESTION;
DROP SEQUENCE "&USUARIO".AACI_SEQ_PAISES;

SPOOL OFF