SPOOL 06_AACID_OWNER_AACI_grants_rollback.log

DEF USUARIO_OWNER=AACID_OWNER;
DEF USUARIO_USER=AACID_USER;

REVOKE SELECT ON "&USUARIO_OWNER".AACI_SEQ_T_CRITERIOS FROM "&USUARIO_USER";
REVOKE DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_T_CRITERIOS FROM "&USUARIO_USER";
REVOKE SELECT ON "&USUARIO_OWNER".AACI_SEQ_CRITERIOS FROM "&USUARIO_USER";
REVOKE DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_CRITERIOS FROM "&USUARIO_USER";
REVOKE SELECT ON "&USUARIO_OWNER".AACI_SEQ_SOLICITUD_CRITERIO FROM "&USUARIO_USER";
REVOKE DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_SOLICITUD_CRITERIO FROM "&USUARIO_USER";
REVOKE SELECT ON "&USUARIO_OWNER".AACI_SEQ_SOLICITUDES_AUXILIAR FROM "&USUARIO_USER";
REVOKE DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_SOLICITUDES_AUXILIAR FROM "&USUARIO_USER";
REVOKE SELECT ON "&USUARIO_OWNER".AACI_SEQ_FINALIDAD FROM "&USUARIO_USER";
REVOKE DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_FINALIDAD FROM "&USUARIO_USER";
REVOKE SELECT ON "&USUARIO_OWNER".AACI_SEQ_GASTOS_FINALIDAD FROM "&USUARIO_USER";
REVOKE DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_GASTOS_FINALIDAD FROM "&USUARIO_USER";
REVOKE SELECT ON "&USUARIO_OWNER".AACI_SEQ_GASTOS FROM "&USUARIO_USER";
REVOKE DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_GASTOS FROM "&USUARIO_USER";
REVOKE SELECT ON "&USUARIO_OWNER".AACI_SEQ_FUNCIONES FROM "&USUARIO_USER";
REVOKE DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_FUNCIONES FROM "&USUARIO_USER";
REVOKE SELECT ON "&USUARIO_OWNER".AACI_SEQ_T_ENT_PARTICIPANTE FROM "&USUARIO_USER";
REVOKE DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_T_ENTIDAD_PARTICIPANTE FROM "&USUARIO_USER";
REVOKE SELECT ON "&USUARIO_OWNER".AACI_SEQ_ENT_PARTICIPANTES FROM "&USUARIO_USER";
REVOKE DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_ENTIDADES_PARTICIPANTES FROM "&USUARIO_USER";
REVOKE SELECT ON "&USUARIO_OWNER".AACI_SEQ_SOLI_TCRITERIO FROM "&USUARIO_USER";
REVOKE DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_SOLICITUD_TCRITERIO FROM "&USUARIO_USER";

REVOKE SELECT ON "&USUARIO_OWNER".AACI_SEQ_PAISES FROM "&USUARIO_USER";
REVOKE DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_T_PAISES FROM "&USUARIO_USER";
REVOKE DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_T_PAISES_SOLICITUD FROM "&USUARIO_USER";

SPOOL OFF