SPOOL 08_AACID_USER_AACI_sinonimos_rollback.log

DEF USUARIO_OWNER=AACID_OWNER;
DEF USUARIO_USER=AACID_USER;

DROP SYNONYM "&USUARIO_USER".AACI_SEQ_T_CRITERIOS;
DROP SYNONYM "&USUARIO_USER".AACI_T_CRITERIOS;
DROP SYNONYM "&USUARIO_USER".AACI_SEQ_CRITERIOS;
DROP SYNONYM "&USUARIO_USER".AACI_CRITERIOS;
DROP SYNONYM "&USUARIO_USER".AACI_SEQ_SOLICITUD_CRITERIO;
DROP SYNONYM "&USUARIO_USER".AACI_SOLICITUD_CRITERIO;
DROP SYNONYM "&USUARIO_USER".AACI_SEQ_SOLICITUDES_AUXILIAR;
DROP SYNONYM "&USUARIO_USER".AACI_SOLICITUDES_AUXILIAR;
DROP SYNONYM "&USUARIO_USER".AACI_SEQ_FINALIDAD;
DROP SYNONYM "&USUARIO_USER".AACI_FINALIDAD;
DROP SYNONYM "&USUARIO_USER".AACI_SEQ_GASTOS_FINALIDAD;
DROP SYNONYM "&USUARIO_USER".AACI_GASTOS_FINALIDAD;
DROP SYNONYM "&USUARIO_USER".AACI_SEQ_GASTOS;
DROP SYNONYM "&USUARIO_USER".AACI_GASTOS;
DROP SYNONYM "&USUARIO_USER".AACI_SEQ_FUNCIONES;
DROP SYNONYM "&USUARIO_USER".AACI_FUNCIONES;
DROP SYNONYM "&USUARIO_USER".AACI_SEQ_T_ENT_PARTICIPANTE;
DROP SYNONYM "&USUARIO_USER".AACI_T_ENTIDAD_PARTICIPANTE;
DROP SYNONYM "&USUARIO_USER".AACI_SEQ_ENT_PARTICIPANTES;
DROP SYNONYM "&USUARIO_USER".AACI_ENTIDADES_PARTICIPANTES;
DROP SYNONYM "&USUARIO_USER".AACI_SEQ_SOLI_TCRITERIO;
DROP SYNONYM "&USUARIO_USER".AACI_SOLICITUD_TCRITERIO;

DROP SYNONYM "&USUARIO_USER".AACI_T_PAISES;
DROP SYNONYM "&USUARIO_USER".AACI_T_PAISES_SOLICITUD;


SPOOL OFF