SPOOL 01_AACID_USER_sinonimos_rollback.log

DEF USUARIO_OWNER=AACID_OWNER;
DEF USUARIO_USER=AACID_USER;

DROP SYNONYM "&USUARIO_USER".AACI_SEQ_REFORMULA;
DROP SYNONYM "&USUARIO_USER".AACI_REFORMULA;

DROP SYNONYM "&USUARIO_USER".AACI_SEQ_SOLICITUD_CONCESION;
DROP SYNONYM "&USUARIO_USER".AACI_SOLICITUD_CONCESION;

DROP SYNONYM "&USUARIO_USER".AACI_TM_ENTIDAD_CONTRAPARTE;


SPOOL OFF