SPOOL 02_AACID_OWNER_grants_rollback.log

DEF USUARIO_OWNER=AACID_OWNER;
DEF USUARIO_USER=AACID_USER;

REVOKE SELECT ON "&USUARIO_OWNER".AACI_SEQ_REFORMULA FROM "&USUARIO_USER";
REVOKE DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_REFORMULA FROM "&USUARIO_USER";

REVOKE SELECT ON "&USUARIO_OWNER".AACI_SEQ_SOLICITUD_CONCESION FROM "&USUARIO_USER";
REVOKE DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_SOLICITUD_CONCESION FROM "&USUARIO_USER";

REVOKE DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_TM_ENTIDAD_CONTRAPARTE FROM "&USUARIO_USER";

SPOOL OFF