SPOOL 03_AACID_OWNER_constraints.log

DEF USUARIO=AACID_OWNER;

ALTER TABLE "&USUARIO".AACI_CONTRAPARTES DROP CONSTRAINT FK_AACI_TM_ENTIDAD_CONTRAPARTE;
ALTER TABLE "&USUARIO".AACI_CONTRAPARTES ADD CONSTRAINT FK_AACI_CONTRAPARTE_ENTIDAD FOREIGN KEY (ENTI_NU_ID) REFERENCES "&USUARIO".AACI_ENTIDAD_CONTRAPARTE (ENTI_NU_ID);


ALTER TABLE "&USUARIO".AACI_CON_OTRAS DROP CONSTRAINT FK_AACI_ENTIDAD;
ALTER TABLE "&USUARIO".AACI_CON_OTRAS ADD CONSTRAINT FK_AACI_ENTIDAD FOREIGN KEY (FK_ENTIDAD) REFERENCES "&USUARIO".AACI_ENTIDAD_CONTRAPARTE (ENTI_NU_ID) ;
SPOOL OFF