SPOOL 05_AACID_OWNER_tablas_rollback.log

DEF USUARIO=AACID_OWNER;

DROP TABLE "&USUARIO".AACI_REFORMULA CASCADE CONSTRAINTS;

--ValidaciOn presupuesto
ALTER TABLE "&USUARIO".AACI_FUNCIONES DROP COLUMN FUNC_TX_CODIGO;

DROP TABLE "&USUARIO".AACI_TM_ENTIDAD_CONTRAPARTE CASCADE CONSTRAINTS;

ALTER TABLE "&USUARIO".AACI_CONTRAPARTES RENAME COLUMN "TMEC_NU_ID" TO "ENTI_NU_ID";

ALTER TABLE "&USUARIO".AACI_T_ENTIDAD_PARTICIPANTE DROP COLUMN "TEPA_TX_CODIGO";

DROP TABLE "&USUARIO".AACI_SOLICITUD_CONCESION CASCADE CONSTRAINTS;

SPOOL OFF