SPOOL 01_AACID_OWNER_AACI_tablas_rollback.log
    
DEF USUARIO=AACID_OWNER;

ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN TX_RESP_REQ_SUBSANACION;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_OCHECKDOC1;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_OCHECKDOC2;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_OCHECKDOC3;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_OCHECKDOC4;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_OCHECKDOC5;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_OCHECKDOC6;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_OCHECKDOC7;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_OCHECKDOC8;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_OCHECKDOC9;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_OCHECKDOC10;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_OCHECKDOC11;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_OCHECKDOC12;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_OCHECKDOC13;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_OCHECKDOC14;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_OCHECKDOC15;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_OCHECKDOC16;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_OCHECKDOC17;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_OCHECKDOC18;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_OCHECKDOC19;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_OCHECKDOC20;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_OCHECKDOC21;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_OCHECKDOC22;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_OCHECKDOC23;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_OCHECKDOC24;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_OCHECKDOC25;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_OCHECKDOC26;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_OCHECKDOC27;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_OCHECKDOC28;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_OCHECKDOC29;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_OCHECKDOC30;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_OCHECKDOC31;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_OCHECKDOC32;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_TCHECKDOC1;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_TCHECKDOC2;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_TCHECKDOC3;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_TCHECKDOC4;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_TCHECKDOC5;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_TCHECKDOC6;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_TCHECKDOC7;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_TCHECKDOC8;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_TCHECKDOC9;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_TCHECKDOC10;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_TCHECKDOC11;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_TCHECKDOC12;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_TCHECKDOC13;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_TCHECKDOC14;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_TCHECKDOC15;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_TCHECKDOC16;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_TCHECKDOC17;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_TCHECKDOC18;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_TCHECKDOC19;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_TCHECKDOC20;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_TCHECKDOC21;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_TCHECKDOC22;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_TCHECKDOC23;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_TCHECKDOC24;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_TCHECKDOC25;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_TCHECKDOC26;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_TCHECKDOC27;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_TCHECKDOC28;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_TCHECKDOC29;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_TCHECKDOC30;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_TCHECKDOC31;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_TCHECKDOC32;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_CHECKDOC4BIS;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_CHECKDOC14BIS;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN ID_UNIVERDIDAD;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN NU_REPR1TLFMOVIL;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN NU_REPR1TELEFONO;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_CHECKDOC8BIS;
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN TX_REPR1EMAIL;

ALTER TABLE "&USUARIO".AACI_AGRUPACIONES MODIFY AGRU_LI_SIGLAS VARCHAR2(15);

ALTER TABLE "&USUARIO".AACI_T_PAISES_SOLICITUD DROP COLUMN ID_PAIS_SOLICITUD;

DROP TABLE "&USUARIO".AACI_T_SOL_OTRAS_SUBVENCIONES CASCADE CONSTRAINTS;
DROP TABLE "&USUARIO".AACI_T_CON_OTRAS_SUBVENCIONES CASCADE CONSTRAINTS;
DROP TABLE "&USUARIO".AACI_T_DOC_PODER_ADMIN_JA CASCADE CONSTRAINTS;
DROP TABLE "&USUARIO".AACI_T_DOC_PODER_OTR_ADMIN CASCADE CONSTRAINTS;
DROP TABLE "&USUARIO".AACI_T_OTR_DOC CASCADE CONSTRAINTS;
DROP TABLE "&USUARIO".AACI_T_UNIVERSIDADES CASCADE CONSTRAINTS;

SPOOL OFF