SPOOL 02_AACID_OWNER_tablas_rollback.log
    
DEF USUARIO=AACID_OWNER;

alter table "&USUARIO".AACI_T_PAISES_SOLICITUD drop constraint AACI_T_PAISES_SOL_UNIQUE;
ALTER TABLE "&USUARIO".AACI_T_PAISES_SOLICITUD drop CONSTRAINT FK_AACI_PAIS_SOL_SOLICITUD;
ALTER TABLE "&USUARIO".AACI_T_PAISES_SOLICITUD drop CONSTRAINT FK_AACI_PAIS_SOL_PAIS;

COMMIT;

SPOOL OFF