SPOOL 08_AACID_USER_AACI_sinonimos_rollback.log

DEF USUARIO_USER=AACID_USER;

DROP SYNONYM "&USUARIO_USER".AACI_SEQ_PAISES_SOLICITUD;
DROP SYNONYM "&USUARIO_USER".AACI_SEQ_SOL_OTRAS_SUB;
DROP SYNONYM "&USUARIO_USER".AACI_T_SOL_OTRAS_SUBVENCIONES;
DROP SYNONYM "&USUARIO_USER".AACI_SEQ_CON_OTRAS_SUB;
DROP SYNONYM "&USUARIO_USER".AACI_T_CON_OTRAS_SUBVENCIONES;
DROP SYNONYM "&USUARIO_USER".AACI_SEQ_DOCS_PODER_JA;
DROP SYNONYM "&USUARIO_USER".AACI_T_DOC_PODER_ADMIN_JA;
DROP SYNONYM "&USUARIO_USER".AACI_SEQ_DOCS_PODER_OTR_ADMIN;
DROP SYNONYM "&USUARIO_USER".AACI_T_DOC_PODER_OTR_ADMIN;
DROP SYNONYM "&USUARIO_USER".AACI_SEQ_OTROS_DOCUMENTOS;
DROP SYNONYM "&USUARIO_USER".AACI_T_OTR_DOC;
DROP SYNONYM "&USUARIO_USER".AACI_SEQ_UNIVERSIDADES;
DROP SYNONYM "&USUARIO_USER".AACI_T_UNIVERSIDADES;

SPOOL OFF