SPOOL 01_AACID_OWNER_tables.log

DEF USUARIO=AACID_OWNER;
DEF TABLESPACE_DATOS=TS_D_AACID_OWNER;

ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (TX_RESP_REQ_SUBSANACION VARCHAR2(4000));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_OCHECKDOC1 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_OCHECKDOC2 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_OCHECKDOC3 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_OCHECKDOC4 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_OCHECKDOC5 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_OCHECKDOC6 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_OCHECKDOC7 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_OCHECKDOC8 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_OCHECKDOC9 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_OCHECKDOC10 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_OCHECKDOC11 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_OCHECKDOC12 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_OCHECKDOC13 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_OCHECKDOC14 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_OCHECKDOC15 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_OCHECKDOC16 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_OCHECKDOC17 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_OCHECKDOC18 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_OCHECKDOC19 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_OCHECKDOC20 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_OCHECKDOC21 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_OCHECKDOC22 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_OCHECKDOC23 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_OCHECKDOC24 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_OCHECKDOC25 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_OCHECKDOC26 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_OCHECKDOC27 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_OCHECKDOC28 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_OCHECKDOC29 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_OCHECKDOC30 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_OCHECKDOC31 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_OCHECKDOC32 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_TCHECKDOC1 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_TCHECKDOC2 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_TCHECKDOC3 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_TCHECKDOC4 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_TCHECKDOC5 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_TCHECKDOC6 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_TCHECKDOC7 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_TCHECKDOC8 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_TCHECKDOC9 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_TCHECKDOC10 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_TCHECKDOC11 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_TCHECKDOC12 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_TCHECKDOC13 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_TCHECKDOC14 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_TCHECKDOC15 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_TCHECKDOC16 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_TCHECKDOC17 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_TCHECKDOC18 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_TCHECKDOC19 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_TCHECKDOC20 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_TCHECKDOC21 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_TCHECKDOC22 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_TCHECKDOC23 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_TCHECKDOC24 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_TCHECKDOC25 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_TCHECKDOC26 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_TCHECKDOC27 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_TCHECKDOC28 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_TCHECKDOC29 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_TCHECKDOC30 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_TCHECKDOC31 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_TCHECKDOC32 NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_CHECKDOC4BIS NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_CHECKDOC14BIS NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (ID_UNIVERDIDAD NUMBER(10));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (NU_REPR1TLFMOVIL NUMBER(10));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (NU_REPR1TELEFONO NUMBER(10));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (LG_CHECKDOC8BIS NUMBER(1));
ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD ADD (TX_REPR1EMAIL VARCHAR2(250 BYTE));

ALTER TABLE "&USUARIO".AACI_AGRUPACIONES MODIFY AGRU_LI_SIGLAS VARCHAR2(20);

ALTER TABLE "&USUARIO".AACI_T_PAISES_SOLICITUD ADD ID_PAIS_SOLICITUD NUMBER(10);

COMMENT ON COLUMN "&USUARIO".AACI_T_PAISES_SOLICITUD.ID_PAIS_SOLICITUD IS 'Identificador del pais solicitud';

CREATE TABLE "&USUARIO".AACI_T_SOL_OTRAS_SUBVENCIONES
(
    ID_SOL_OTR_SUBVEN NUMBER(10, 0),
    ID_SOLICITUD      NUMBER(10, 0),
    FH_FECHA          NUMBER(4, 0),
    TX_ADM_SOLICITA   VARCHAR(500),
    NU_IMPORTE        NUMBER(10, 0),
    LG_MINIMIS        NUMBER(1, 0)
)
    TABLESPACE "&TABLESPACE_DATOS";

COMMENT ON COLUMN "&USUARIO".AACI_T_SOL_OTRAS_SUBVENCIONES.ID_SOL_OTR_SUBVEN IS 'Identificador de la solicitud solicitada';
COMMENT ON COLUMN "&USUARIO".AACI_T_SOL_OTRAS_SUBVENCIONES.ID_SOLICITUD IS 'Identificador de la solicitud asociada';
COMMENT ON COLUMN "&USUARIO".AACI_T_SOL_OTRAS_SUBVENCIONES.FH_FECHA IS 'Fecha de la solicitud';
COMMENT ON COLUMN "&USUARIO".AACI_T_SOL_OTRAS_SUBVENCIONES.TX_ADM_SOLICITA IS 'Nombre de la adiministración que solicita';
COMMENT ON COLUMN "&USUARIO".AACI_T_SOL_OTRAS_SUBVENCIONES.NU_IMPORTE IS 'Importe de la subvención';
COMMENT ON COLUMN "&USUARIO".AACI_T_SOL_OTRAS_SUBVENCIONES.LG_MINIMIS IS 'Minimis (S/N)';

CREATE TABLE "&USUARIO".AACI_T_CON_OTRAS_SUBVENCIONES
(
    ID_CON_OTR_SUBVEN NUMBER(10, 0),
    ID_SOLICITUD      NUMBER(10, 0),
    FH_FECHA          NUMBER(4, 0),
    TX_ADM_CONCEDE    VARCHAR(500),
    NU_IMPORTE        NUMBER(10, 0),
    LG_MINIMIS        NUMBER(1, 0)
)
    TABLESPACE "&TABLESPACE_DATOS";

COMMENT ON COLUMN "&USUARIO".AACI_T_CON_OTRAS_SUBVENCIONES.ID_con_OTR_SUBVEN IS 'Identificador de la solicitud concedida';
COMMENT ON COLUMN "&USUARIO".AACI_T_CON_OTRAS_SUBVENCIONES.ID_SOLICITUD IS 'Identificador de la solicitud asociada';
COMMENT ON COLUMN "&USUARIO".AACI_T_CON_OTRAS_SUBVENCIONES.FH_FECHA IS 'Fecha de la solicitud';
COMMENT ON COLUMN "&USUARIO".AACI_T_CON_OTRAS_SUBVENCIONES.TX_ADM_CONCEDE IS 'Nombre de la adiministración que concedió la subvención';
COMMENT ON COLUMN "&USUARIO".AACI_T_CON_OTRAS_SUBVENCIONES.NU_IMPORTE IS 'Importe de la subvención';
COMMENT ON COLUMN "&USUARIO".AACI_T_CON_OTRAS_SUBVENCIONES.LG_MINIMIS IS 'Minimis (S/N)';


CREATE TABLE "&USUARIO".AACI_T_DOC_PODER_ADMIN_JA
(
    ID_DOC_PODER_ADMIN_JA  NUMERIC(10, 0),
    ID_SOLICITUD           NUMERIC(10, 0),
    TX_NOM_DOCUMENTO       VARCHAR(100),
    TX_CONSEJERIA_Y_ORGANO VARCHAR(100),
    FH_FECHA_PRESENT       DATE,
    TX_PROCED_EMITIO       VARCHAR(100)
)
    TABLESPACE "&TABLESPACE_DATOS";

COMMENT ON COLUMN "&USUARIO".AACI_T_DOC_PODER_ADMIN_JA.ID_DOC_PODER_ADMIN_JA IS 'Identificador deL documento en posesión de la Administración de la Junta de Andalucía';
COMMENT ON COLUMN "&USUARIO".AACI_T_DOC_PODER_ADMIN_JA.ID_SOLICITUD IS 'Identificador de la solicitud asociada';
COMMENT ON COLUMN "&USUARIO".AACI_T_DOC_PODER_ADMIN_JA.TX_NOM_DOCUMENTO IS 'Nombre del documento de la Junta de Andalucía';
COMMENT ON COLUMN "&USUARIO".AACI_T_DOC_PODER_ADMIN_JA.TX_CONSEJERIA_Y_ORGANO IS 'Consejería/Agencia y Órgano';
COMMENT ON COLUMN "&USUARIO".AACI_T_DOC_PODER_ADMIN_JA.FH_FECHA_PRESENT IS 'Fecha de emisión o presentación del documento';
COMMENT ON COLUMN "&USUARIO".AACI_T_DOC_PODER_ADMIN_JA.TX_PROCED_EMITIO IS 'Procedimiento en el que se emitió o en el que se presentó el documento';

CREATE TABLE "&USUARIO".AACI_T_DOC_PODER_OTR_ADMIN
(
    ID_DOC_PODER_OTR_ADMIN NUMBER(10, 0),
    ID_SOLICITUD           NUMBER(10, 0),
    TX_NOM_DOCUMENTO       VARCHAR(100),
    TX_CONSEJERIA_Y_ORGANO VARCHAR(100),
    FH_FECHA_PRESENT       DATE,
    TX_PROCED_EMITIO       VARCHAR(100)
)
    TABLESPACE "&TABLESPACE_DATOS";

COMMENT ON COLUMN "&USUARIO".AACI_T_DOC_PODER_OTR_ADMIN.ID_DOC_PODER_OTR_ADMIN IS 'Identificador del documento en posesión de otra Administración';
COMMENT ON COLUMN "&USUARIO".AACI_T_DOC_PODER_OTR_ADMIN.ID_SOLICITUD IS 'Identificador de la solicitud asociada';
COMMENT ON COLUMN "&USUARIO".AACI_T_DOC_PODER_OTR_ADMIN.TX_NOM_DOCUMENTO IS 'Nombre del documento de otra administración';
COMMENT ON COLUMN "&USUARIO".AACI_T_DOC_PODER_OTR_ADMIN.TX_CONSEJERIA_Y_ORGANO IS 'Consejería/Agencia y Órgano';
COMMENT ON COLUMN "&USUARIO".AACI_T_DOC_PODER_OTR_ADMIN.FH_FECHA_PRESENT IS 'Fecha de emisión o presentación del documento';
COMMENT ON COLUMN "&USUARIO".AACI_T_DOC_PODER_OTR_ADMIN.TX_PROCED_EMITIO IS 'Procedimiento en el que se emitió o en el que se presentó el documento';

CREATE TABLE "&USUARIO".AACI_T_OTR_DOC
(
    ID_OTR_DOC     NUMBER(10, 0),
    ID_SOLICITUD   NUMBER(10, 0),
    TX_DESCRIPCION VARCHAR(150)
)
    TABLESPACE "&TABLESPACE_DATOS";

COMMENT ON COLUMN "&USUARIO".AACI_T_OTR_DOC.ID_OTR_DOC IS 'Identificador del otro documento';
COMMENT ON COLUMN "&USUARIO".AACI_T_OTR_DOC.ID_SOLICITUD IS 'Identificador de la solicitud asociada';
COMMENT ON COLUMN "&USUARIO".AACI_T_OTR_DOC.TX_DESCRIPCION IS 'Descripción del otro documento';

CREATE TABLE "&USUARIO".AACI_T_UNIVERSIDADES
(
    ID_UNIVERSIDAD NUMBER(19, 0),
    TX_CODIGO      VARCHAR2(100),
    TX_NOMBRE      VARCHAR2(500)
)
    TABLESPACE "&TABLESPACE_DATOS";

COMMENT ON COLUMN "&USUARIO".AACI_T_UNIVERSIDADES.ID_UNIVERSIDAD IS 'Identificador de la universidad';
COMMENT ON COLUMN "&USUARIO".AACI_T_UNIVERSIDADES.TX_CODIGO IS 'código de la universidad';
COMMENT ON COLUMN "&USUARIO".AACI_T_UNIVERSIDADES.TX_NOMBRE IS 'Nombre de la universidad';


SPOOL OFF