SPOOL 03_AACID_OWNER_inserts.log

DEF USUARIO=AACID_OWNER;

Insert into "&USUARIO".AACI_EXCLUSION values ("&USUARIO".AACI_SEQ_EXCLUSION.NEXTVAL,(SELECT TEXC_NU_ID FROM "&USUARIO".AACI_TIPO_EXCLUSION WHERE TEXC_NU_ORDEN= 1 AND TEXC_NU_TIPO = 3 and TCONV_NU_ID = (SELECT TCONV_NU_ID FROM "&USUARIO".AACI_T_TIPO_CONV WHERE TCONV_LI_DENOMINACION = 'UNIV')),'Excluido por no recoger en la formulación las mejoras en proyectos de continuidad financiados por la AACID. (art. 4.5).','VALORADOR,COORDINADOR',38,2021);
Insert into "&USUARIO".AACI_EXCLUSION values ("&USUARIO".AACI_SEQ_EXCLUSION.NEXTVAL,(SELECT TEXC_NU_ID FROM "&USUARIO".AACI_TIPO_EXCLUSION WHERE TEXC_NU_ORDEN= 1 AND TEXC_NU_TIPO = 3 and TCONV_NU_ID = (SELECT TCONV_NU_ID FROM "&USUARIO".AACI_T_TIPO_CONV WHERE TCONV_LI_DENOMINACION = 'UNIV')),'Desestimado por no obtener una valoración total mínima de 55 puntos (art. 4.6).','VALORADOR,COORDINADOR',39,2021);
Insert into "&USUARIO".AACI_EXCLUSION values ("&USUARIO".AACI_SEQ_EXCLUSION.NEXTVAL,(SELECT TEXC_NU_ID FROM "&USUARIO".AACI_TIPO_EXCLUSION WHERE TEXC_NU_ORDEN= 1 AND TEXC_NU_TIPO = 3 and TCONV_NU_ID = (SELECT TCONV_NU_ID FROM "&USUARIO".AACI_T_TIPO_CONV WHERE TCONV_LI_DENOMINACION = 'UNIV')),'Desestimado por no alcanzar la mitad de la puntuación máxima en el criterio de Pertinencia (art. 7.1.a) y art. 4.6).','VALORADOR,COORDINADOR',40,2021);
Insert into "&USUARIO".AACI_EXCLUSION values ("&USUARIO".AACI_SEQ_EXCLUSION.NEXTVAL,(SELECT TEXC_NU_ID FROM "&USUARIO".AACI_TIPO_EXCLUSION WHERE TEXC_NU_ORDEN= 1 AND TEXC_NU_TIPO = 3 and TCONV_NU_ID = (SELECT TCONV_NU_ID FROM "&USUARIO".AACI_T_TIPO_CONV WHERE TCONV_LI_DENOMINACION = 'UNIV')),'Desestimado por no alcanzar la mitad de la puntuación máxima en el criterio de Viabilidad (art. 7.1.b) y art. 4.6).','VALORADOR,COORDINADOR',41,2021);
Insert into "&USUARIO".AACI_EXCLUSION values ("&USUARIO".AACI_SEQ_EXCLUSION.NEXTVAL,(SELECT TEXC_NU_ID FROM "&USUARIO".AACI_TIPO_EXCLUSION WHERE TEXC_NU_ORDEN= 1 AND TEXC_NU_TIPO = 3 and TCONV_NU_ID = (SELECT TCONV_NU_ID FROM "&USUARIO".AACI_T_TIPO_CONV WHERE TCONV_LI_DENOMINACION = 'UNIV')),'Desestimado por no alcanzar la mitad de la puntuación máxima en el criterio de Coherencia (art. 7.1.c) y art. 4.6).','VALORADOR,COORDINADOR',42,2021);
Insert into "&USUARIO".AACI_EXCLUSION values ("&USUARIO".AACI_SEQ_EXCLUSION.NEXTVAL,(SELECT TEXC_NU_ID FROM "&USUARIO".AACI_TIPO_EXCLUSION WHERE TEXC_NU_ORDEN= 1 AND TEXC_NU_TIPO = 3 and TCONV_NU_ID = (SELECT TCONV_NU_ID FROM "&USUARIO".AACI_T_TIPO_CONV WHERE TCONV_LI_DENOMINACION = 'UNIV')),'Desestimado por no alcanzar la mitad de la puntuación máxima en el criterio de Sostenibilidad (art. 7.1.d) y art. 4.6).','VALORADOR,COORDINADOR',43,2021);
Insert into "&USUARIO".AACI_EXCLUSION values ("&USUARIO".AACI_SEQ_EXCLUSION.NEXTVAL,(SELECT TEXC_NU_ID FROM "&USUARIO".AACI_TIPO_EXCLUSION WHERE TEXC_NU_ORDEN= 1 AND TEXC_NU_TIPO = 3 and TCONV_NU_ID = (SELECT TCONV_NU_ID FROM "&USUARIO".AACI_T_TIPO_CONV WHERE TCONV_LI_DENOMINACION = 'UNIV')),'Desestimado por no alcanzar la mitad de la puntuación máxima en el criterio de Impacto (art. 7.1.e) y art. 4.6).','VALORADOR,COORDINADOR',44,2021);
COMMIT;


Insert into "&USUARIO".AACI_T_PAISES (ID_PAIS, TX_CODIGO, TX_NOMBRE, NU_ANIO, NU_PUNTUACION)
values ("&USUARIO".AACI_SEQ_PAISES.nextval, '27', 'Andalucía', 2021, null);
COMMIT;

Insert into "&USUARIO".AACI_T_UNIVERSIDADES (ID_UNIVERSIDAD, TX_CODIGO, TX_NOMBRE)
values ("&USUARIO".AACI_SEQ_UNIVERSIDADES.NEXTVAL, '1', 'Universidad de Almería');
Insert into "&USUARIO".AACI_T_UNIVERSIDADES (ID_UNIVERSIDAD, TX_CODIGO, TX_NOMBRE)
values ("&USUARIO".AACI_SEQ_UNIVERSIDADES.NEXTVAL, '2', 'Universidad de Cádiz');
Insert into "&USUARIO".AACI_T_UNIVERSIDADES (ID_UNIVERSIDAD, TX_CODIGO, TX_NOMBRE)
values ("&USUARIO".AACI_SEQ_UNIVERSIDADES.NEXTVAL, '3', 'Universidad de Córdoba');
Insert into "&USUARIO".AACI_T_UNIVERSIDADES (ID_UNIVERSIDAD, TX_CODIGO, TX_NOMBRE)
values ("&USUARIO".AACI_SEQ_UNIVERSIDADES.NEXTVAL, '4', 'Universidad de Granada');
Insert into "&USUARIO".AACI_T_UNIVERSIDADES (ID_UNIVERSIDAD, TX_CODIGO, TX_NOMBRE)
values ("&USUARIO".AACI_SEQ_UNIVERSIDADES.NEXTVAL, '5', 'Universidad de Huelva');
Insert into "&USUARIO".AACI_T_UNIVERSIDADES (ID_UNIVERSIDAD, TX_CODIGO, TX_NOMBRE)
values ("&USUARIO".AACI_SEQ_UNIVERSIDADES.NEXTVAL, '6', 'Universidad de Jaén');
Insert into "&USUARIO".AACI_T_UNIVERSIDADES (ID_UNIVERSIDAD, TX_CODIGO, TX_NOMBRE)
values ("&USUARIO".AACI_SEQ_UNIVERSIDADES.NEXTVAL, '7', 'Universidad de Málaga');
Insert into "&USUARIO".AACI_T_UNIVERSIDADES (ID_UNIVERSIDAD, TX_CODIGO, TX_NOMBRE)
values ("&USUARIO".AACI_SEQ_UNIVERSIDADES.NEXTVAL, '8', 'Universidad de Sevilla');
Insert into "&USUARIO".AACI_T_UNIVERSIDADES (ID_UNIVERSIDAD, TX_CODIGO, TX_NOMBRE)
values ("&USUARIO".AACI_SEQ_UNIVERSIDADES.NEXTVAL, '9', 'Universidad Internacional de Andalucía');
Insert into "&USUARIO".AACI_T_UNIVERSIDADES (ID_UNIVERSIDAD, TX_CODIGO, TX_NOMBRE)
values ("&USUARIO".AACI_SEQ_UNIVERSIDADES.NEXTVAL, '10', 'Universidad Loyola Andalucía ');
Insert into "&USUARIO".AACI_T_UNIVERSIDADES (ID_UNIVERSIDAD, TX_CODIGO, TX_NOMBRE)
values ("&USUARIO".AACI_SEQ_UNIVERSIDADES.NEXTVAL, '11', 'Universidad Pablo de Olavide');
COMMIT;

SPOOL OFF