SPOOL 04_AACI_constraints.log

DEF USUARIO=AACID_OWNER;
DEF TABLESPACE_INDICES=TS_I_AACID_OWNER;

ALTER TABLE "&USUARIO".AACI_T_PAISES_SOLICITUD
    ADD CONSTRAINT AACI_T_PAISES_SOL_PK PRIMARY KEY (ID_PAIS_SOLICITUD) USING INDEX TABLESPACE "&TABLESPACE_INDICES";
ALTER TABLE "&USUARIO".AACI_T_SOL_OTRAS_SUBVENCIONES
    ADD CONSTRAINT AACI_T_SOL_OTR_SUBVEN_PK PRIMARY KEY (ID_SOL_OTR_SUBVEN) USING INDEX TABLESPACE "&TABLESPACE_INDICES";
ALTER TABLE "&USUARIO".AACI_T_CON_OTRAS_SUBVENCIONES
    ADD CONSTRAINT AACI_T_CON_OTR_SUBVEN_PK PRIMARY KEY (ID_CON_OTR_SUBVEN) USING INDEX TABLESPACE "&TABLESPACE_INDICES";
ALTER TABLE "&USUARIO".AACI_T_DOC_PODER_ADMIN_JA
    ADD CONSTRAINT AACI_T_DOC_PODER_ADMIN_JA_PK PRIMARY KEY (ID_DOC_PODER_ADMIN_JA) USING INDEX TABLESPACE "&TABLESPACE_INDICES";
ALTER TABLE "&USUARIO".AACI_T_DOC_PODER_OTR_ADMIN
    ADD CONSTRAINT AACI_T_DOC_PODER_OTR_ADMIN_PK PRIMARY KEY (ID_DOC_PODER_OTR_ADMIN) USING INDEX TABLESPACE "&TABLESPACE_INDICES";
alter table "&USUARIO".AACI_T_OTR_DOC
    add constraint AACI_T_OTR_DOC_SOL_PK PRIMARY KEY (ID_OTR_DOC) USING INDEX TABLESPACE "&TABLESPACE_INDICES";
ALTER TABLE "&USUARIO".AACI_T_UNIVERSIDADES
    ADD CONSTRAINT AACI_T_UNIVERSIDADES_PK PRIMARY KEY (ID_UNIVERSIDAD) USING INDEX TABLESPACE "&TABLESPACE_INDICES";

ALTER TABLE "&USUARIO".AACI_T_PAISES_SOLICITUD
    ADD CONSTRAINT FK_AACI_PAIS_SOL_SOLICITUD FOREIGN KEY (ID_SOLICITUD) REFERENCES "&USUARIO".AACI_T_SOLICITUDSUBONGD (ID_SOLICITUD);
ALTER TABLE "&USUARIO".AACI_T_PAISES_SOLICITUD
    ADD CONSTRAINT FK_AACI_PAIS_SOL_PAIS FOREIGN KEY (ID_PAIS) REFERENCES "&USUARIO".AACI_T_PAISES (ID_PAIS);

ALTER TABLE "&USUARIO".AACI_T_SOL_OTRAS_SUBVENCIONES
    ADD CONSTRAINT FK_AACI_SOL_OTR_SUBVEN_SOL FOREIGN KEY (ID_SOLICITUD) REFERENCES "&USUARIO".AACI_T_SOLICITUDSUBONGD (ID_SOLICITUD);
ALTER TABLE "&USUARIO".AACI_T_CON_OTRAS_SUBVENCIONES
    ADD CONSTRAINT FK_AACI_CON_OTR_SUBVEN_SOL FOREIGN KEY (ID_SOLICITUD) REFERENCES "&USUARIO".AACI_T_SOLICITUDSUBONGD (ID_SOLICITUD);

ALTER TABLE "&USUARIO".AACI_T_DOC_PODER_ADMIN_JA
    ADD CONSTRAINT FK_AACI_T_DOC_ADMIN_JA_SOL FOREIGN KEY (ID_SOLICITUD) REFERENCES "&USUARIO".AACI_T_SOLICITUDSUBONGD (ID_SOLICITUD);
ALTER TABLE "&USUARIO".AACI_T_DOC_PODER_OTR_ADMIN
    ADD CONSTRAINT FK_AACI_T_DOC_OTR_ADMIN_SOL FOREIGN KEY (ID_SOLICITUD) REFERENCES "&USUARIO".AACI_T_SOLICITUDSUBONGD (ID_SOLICITUD);

ALTER TABLE "&USUARIO".AACI_T_OTR_DOC
    ADD CONSTRAINT FK_AACI_SOL_OTR_DOC FOREIGN KEY (ID_SOLICITUD) REFERENCES "&USUARIO".AACI_T_SOLICITUDSUBONGD (ID_SOLICITUD);

ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD
    ADD CONSTRAINT FK_AACI_SOL_UNIV FOREIGN KEY (ID_UNIVERDIDAD) REFERENCES "&USUARIO".AACI_T_UNIVERSIDADES (ID_UNIVERSIDAD);

alter table "&USUARIO".AACI_T_PAISES_SOLICITUD
    add constraint AACI_T_PAISES_SOL_UNIQUE unique (ID_SOLICITUD, ID_PAIS);

SPOOL OFF