SPOOL 06_ACCI_grants.log

DEF USUARIO_OWNER=AACID_OWNER;
DEF USUARIO_USER=AACID_USER;

GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_PAISES_SOLICITUD TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_SOL_OTRAS_SUB TO "&USUARIO_USER";
GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_T_SOL_OTRAS_SUBVENCIONES TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_CON_OTRAS_SUB TO "&USUARIO_USER";
GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_T_CON_OTRAS_SUBVENCIONES TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_DOCS_PODER_JA TO "&USUARIO_USER";
GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_T_DOC_PODER_ADMIN_JA TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_DOCS_PODER_OTR_ADMIN TO "&USUARIO_USER";
GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_T_DOC_PODER_OTR_ADMIN TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_OTROS_DOCUMENTOS TO "&USUARIO_USER";
GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_T_OTR_DOC TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_UNIVERSIDADES TO "&USUARIO_USER";
GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_T_UNIVERSIDADES TO "&USUARIO_USER";

SPOOL OFF