SPOOL 08_ACCI_sinonimos.log

DEF USUARIO_OWNER=AACID_OWNER;
DEF USUARIO_USER=AACID_USER;

CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_PAISES_SOLICITUD FOR "&USUARIO_OWNER".AACI_SEQ_PAISES_SOLICITUD;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_SOL_OTRAS_SUB FOR "&USUARIO_OWNER".AACI_SEQ_SOL_OTRAS_SUB;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_T_SOL_OTRAS_SUBVENCIONES FOR "&USUARIO_OWNER".AACI_T_SOL_OTRAS_SUBVENCIONES;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_CON_OTRAS_SUB FOR "&USUARIO_OWNER".AACI_SEQ_CON_OTRAS_SUB;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_T_CON_OTRAS_SUBVENCIONES FOR "&USUARIO_OWNER".AACI_T_CON_OTRAS_SUBVENCIONES;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_DOCS_PODER_JA FOR "AACID_OWNER".AACI_SEQ_DOCS_PODER_JA;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_T_DOC_PODER_ADMIN_JA FOR "&USUARIO_OWNER".AACI_T_DOC_PODER_ADMIN_JA;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_DOCS_PODER_OTR_ADMIN FOR "&USUARIO_OWNER".AACI_SEQ_DOCS_PODER_OTR_ADMIN;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_T_DOC_PODER_OTR_ADMIN FOR "&USUARIO_OWNER".AACI_T_DOC_PODER_OTR_ADMIN;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_AGRUPACION FOR "&USUARIO_OWNER".AACI_SEQ_AGRUPACION;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_AGRUPACIONES FOR "&USUARIO_OWNER".AACI_AGRUPACIONES;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_OTROS_DOCUMENTOS FOR "&USUARIO_OWNER".AACI_SEQ_OTROS_DOCUMENTOS;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_T_OTR_DOC FOR "&USUARIO_OWNER".AACI_T_OTR_DOC;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_UNIVERSIDADES FOR "&USUARIO_OWNER".AACI_SEQ_UNIVERSIDADES;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_T_UNIVERSIDADES FOR "&USUARIO_OWNER".AACI_T_UNIVERSIDADES;


SPOOL OFF