SPOOL 11_AACID_OWNER_inserts_correccion_capacidad_gestion.log
    
DEF USUARIO=AACID_OWNER;

UPDATE "&USUARIO".AACI_TM_CAPACIDAD_GESTION SET TMCG_NU_PUNT_TOTAL=0.583 WHERE TMCG_TX_CIF ='G58236803';
commit;

SPOOL OFF