SPOOL 01_AACID_OWNER_alter_table_rollback.log

DEF USUARIO=AACID_OWNER;

--Procesamiento Específico--

ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN "FH_INICIOCOM";

ALTER TABLE "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN "FH_FINCOM";

SPOOL OFF