SPOOL 03_AACI_constraints.log

DEF USUARIO=AACID_OWNER;
DEF TABLESPACE_INDICES=TS_I_AACID_OWNER;

ALTER TABLE "&USUARIO".AACI_TEXCLUSIONES_SOLICITUD ADD CONSTRAINT AACI_TEXCLUSIONES_SOLICITUD_PK PRIMARY KEY ( TESO_NU_ID ) USING INDEX TABLESPACE "&TABLESPACE_INDICES";

ALTER TABLE "&USUARIO".AACI_TEXCLUSIONES_SOLICITUD ADD CONSTRAINT FK_AACI_T_SOLICITUDSUBONGD FOREIGN KEY ( ID_SOLICITUD ) REFERENCES "&USUARIO".AACI_T_SOLICITUDSUBONGD(ID_SOLICITUD);

SPOOL OFF