SPOOL 05_ACCI_sinonimos.log

DEF USUARIO_OWNER=AACID_OWNER;
DEF USUARIO_USER=AACID_USER;

CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_TEXCLU_SOLICITUD FOR "&USUARIO_OWNER".AACI_SEQ_TEXCLU_SOLICITUD;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_TEXCLUSIONES_SOLICITUD FOR "&USUARIO_OWNER".AACI_TEXCLUSIONES_SOLICITUD;

SPOOL OFF