SPOOL 01_AACI_tablas.log
  
  DEF USUARIO=AACID_OWNER;
  DEF TABLESPACE_DATOS=TS_D_AACID_OWNER;

  CREATE TABLE "&USUARIO".AACI_CONVOCATORIA_FECHAS (
    CONVF_NU_ID NUMBER (19,0) NOT null,
    CONV_NU_ID NUMBER (10,0) NOT null,
    CONVF_CO_FASE VARCHAR2(100) NOT null,
    CONVF_LI_FASE VARCHAR2(250),
    CONVF_FH_APERTURA DATE NOT null,
    CONVF_FH_CIERRE DATE NOT NULL ENABLE 
  )
  TABLESPACE "&TABLESPACE_DATOS" LOGGING;


  COMMENT ON TABLE "&USUARIO".AACI_CONVOCATORIA_FECHAS IS 'TABLA PARA EL GUARDADO DE LAS FECHAS DE APERTURA Y CIERRE DE LAS FASES DE RECEPCIÓN';
  COMMENT ON COLUMN "&USUARIO".AACI_CONVOCATORIA_FECHAS.CONVF_NU_ID IS 'ID DE LA TABLA';
  COMMENT ON COLUMN "&USUARIO".AACI_CONVOCATORIA_FECHAS.CONV_NU_ID IS 'ID DE LA CONVOCATORIA RELACIONADA';
  COMMENT ON COLUMN "&USUARIO".AACI_CONVOCATORIA_FECHAS.CONVF_CO_FASE IS 'CÓDIGO DE LA FASE';
  COMMENT ON COLUMN "&USUARIO".AACI_CONVOCATORIA_FECHAS.CONVF_LI_FASE IS 'DESCRIPCIÓN DE LA FASE';
  COMMENT ON COLUMN "&USUARIO".AACI_CONVOCATORIA_FECHAS.CONVF_FH_APERTURA IS 'FECHA APERTURA';
  COMMENT ON COLUMN "&USUARIO".AACI_CONVOCATORIA_FECHAS.CONVF_FH_CIERRE IS 'FECHA CIERRE';
  
    
SPOOL OFF