SPOOL 03_AACI_constraints.log

DEF USUARIO=AACID_OWNER;
DEF TABLESPACE_INDICES=TS_I_AACID_OWNER;

ALTER TABLE "&USUARIO".AACI_CONVOCATORIA_FECHAS ADD CONSTRAINT AACI_CONVOCATORIA_FECHAS_PK PRIMARY KEY ( CONVF_NU_ID ) USING INDEX TABLESPACE "&TABLESPACE_INDICES";

ALTER TABLE "&USUARIO".AACI_CONVOCATORIA_FECHAS ADD CONSTRAINT AACI_CONV_FH_CONV_FK FOREIGN KEY ( CONV_NU_ID ) REFERENCES "&USUARIO".AACI_T_CONVOCATORIAS(CONV_NU_ID);

SPOOL OFF