SPOOL 05_ACCI_sinonimos.log

DEF USUARIO_OWNER=AACID_OWNER;
DEF USUARIO_USER=AACID_USER;

CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_CONVOCATORIA_FECHAS FOR "&USUARIO_OWNER".AACI_SEQ_CONVOCATORIA_FECHAS;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_CONVOCATORIA_FECHAS FOR "&USUARIO_OWNER".AACI_CONVOCATORIA_FECHAS;

SPOOL OFF