SPOOL 04_ACCI_sinonimos_rollback.log

DEF USUARIO_OWNER=AACID_OWNER;
DEF USUARIO_USER=AACID_USER;

DROP PUBLIC SYNONYM "&USUARIO_USER".AACI_SEQ_CONVOCATORIA_FECHAS;
DROP PUBLIC SYNONYM "&USUARIO_USER".AACI_CONVOCATORIA_FECHAS;

SPOOL OFF