SPOOL 01_AACI_inserts_2.log

DEF USUARIO=AACID_OWNER;

INSERT into "&USUARIO".AACI_EXCLUSIONES_SOLICITUD (excl_nu_id, soli_nu_id) VALUES ((SELECT EXCL_NU_ID FROM "&USUARIO".AACI_EXCLUSION ae INNER JOIN "&USUARIO".AACI_TIPO_EXCLUSION ate ON ate.TEXC_NU_ID = ae.TEXC_NU_ID INNER JOIN "&USUARIO".AACI_T_TIPO_CONV attc ON attc.TCONV_NU_ID = ate.TCONV_NU_ID WHERE attc.TCONV_LI_DENOMINACION ='UNIV' AND excl_nu_orden = 59), 28);
INSERT into "&USUARIO".AACI_EXCLUSIONES_SOLICITUD (excl_nu_id, soli_nu_id) VALUES ((SELECT EXCL_NU_ID FROM "&USUARIO".AACI_EXCLUSION ae INNER JOIN "&USUARIO".AACI_TIPO_EXCLUSION ate ON ate.TEXC_NU_ID = ae.TEXC_NU_ID INNER JOIN "&USUARIO".AACI_T_TIPO_CONV attc ON attc.TCONV_NU_ID = ate.TCONV_NU_ID WHERE attc.TCONV_LI_DENOMINACION ='UNIV' AND excl_nu_orden = 59), 29);

COMMIT;

SPOOL OFF