SPOOL 03_AACI_PRO_Updates.log

DEF USUARIO=AACID_OWNER;

update "&USUARIO".AACI_SOLICITUD_TCRITERIO set SOTC_NU_PUNTUACION_TOTAL=0 where ID_SOLICITUD = 211 and TCRI_NU_ID = 54;
update "&USUARIO".AACI_SOLICITUD_TCRITERIO set SOTC_NU_PUNTUACION_TOTAL=0 where ID_SOLICITUD = 318 and TCRI_NU_ID = 54;
update "&USUARIO".AACI_SOLICITUD_TCRITERIO set SOTC_NU_PUNTUACION_TOTAL=0 where ID_SOLICITUD = 99 and TCRI_NU_ID = 61;
update "&USUARIO".AACI_SOLICITUD_TCRITERIO set SOTC_NU_PUNTUACION_TOTAL=0 where ID_SOLICITUD = 122 and TCRI_NU_ID = 61;

COMMIT;

SPOOL OFF