SPOOL 04_AACI_PRO_Updates.log

DEF USUARIO=AACID_OWNER;

update "&USUARIO".AACI_SOLICITUD_TCRITERIO set SOTC_NU_PUNTUACION_TOTAL=0 where ID_SOLICITUD = 211 and TCRI_NU_ID = 53;
update "&USUARIO".AACI_SOLICITUD_TCRITERIO set SOTC_NU_PUNTUACION_TOTAL=0 where ID_SOLICITUD = 211 and TCRI_NU_ID = 55;
update "&USUARIO".AACI_SOLICITUD_TCRITERIO set SOTC_NU_PUNTUACION_TOTAL=0 where ID_SOLICITUD = 318 and TCRI_NU_ID = 53;

COMMIT;

SPOOL OFF