SPOOL 01_AACID_OWNER_AACI_tablas.log
    
DEF USUARIO=AACID_OWNER;
DEF TABLESPACE_DATOS=TS_D_AACID_OWNER;

CREATE TABLE "&USUARIO".AACI_REFORMULA (
	ID_REFORMULA NUMBER(19,0) NOT NULL,
	ID_SOLICITUD NUMBER(19,0) NOT NULL,
	NU_MAXIMO NUMBER(20,2) NOT NULL,
	NU_MINIMO NUMBER(20,2) NOT NULL,
	TX_TIPO VARCHAR2(1 CHAR)
) TABLESPACE "&TABLESPACE_DATOS";

COMMENT ON TABLE "&USUARIO".AACI_REFORMULA IS 'Tabla que almacena los datos de reformulación de las solicitudes';
COMMENT ON COLUMN "&USUARIO".AACI_REFORMULA.ID_REFORMULA IS 'Identificador de la reformulación';
COMMENT ON COLUMN "&USUARIO".AACI_REFORMULA.ID_SOLICITUD IS 'FK de la Solicitud';
COMMENT ON COLUMN "&USUARIO".AACI_REFORMULA.NU_MAXIMO IS 'Importe máximo';
COMMENT ON COLUMN "&USUARIO".AACI_REFORMULA.NU_MINIMO IS 'Importe mínimo presupuesto total';
COMMENT ON COLUMN "&USUARIO".AACI_REFORMULA.TX_TIPO IS 'Tipo de reformulación';

--Validación Presupuesto--

ALTER TABLE "&USUARIO".AACI_FUNCIONES
ADD FUNC_TX_CODIGO varchar(50 CHAR);


CREATE TABLE "&USUARIO".AACI_TM_ENTIDAD_CONTRAPARTE
(TMEC_NU_ID NUMBER(19,0),
TMEC_TX_DESCRIPTION VARCHAR(50),
TMEC_TX_CODIGO VARCHAR(3))
TABLESPACE "&TABLESPACE_DATOS";

COMMENT ON COLUMN "&USUARIO".AACI_TM_ENTIDAD_CONTRAPARTE.TMEC_NU_ID IS 'Identificador del tipo entidad contraparte';
COMMENT ON COLUMN "&USUARIO".AACI_TM_ENTIDAD_CONTRAPARTE.TMEC_TX_DESCRIPTION IS 'Descripcion del tipo entidad contraparte';
COMMENT ON COLUMN "&USUARIO".AACI_TM_ENTIDAD_CONTRAPARTE.TMEC_TX_CODIGO IS 'Codigo del tipo entidad contraparte';


ALTER TABLE "&USUARIO".AACI_CONTRAPARTES RENAME COLUMN "ENTI_NU_ID" TO "TMEC_NU_ID";

ALTER TABLE "&USUARIO".AACI_T_ENTIDAD_PARTICIPANTE ADD "TEPA_TX_CODIGO" VARCHAR(20 CHAR);


CREATE TABLE "&USUARIO".AACI_SOLICITUD_CONCESION
(SOCO_NU_ID NUMBER(19,0),
SOCO_NU_SOLICITUD NUMBER(19,0),
SOCO_TX_TIPO_CONCESION VARCHAR(25),
SOCO_NU_PRESUPUESTO_VALIDADO NUMBER(25,3),
SOCO_NU_SUBVENCION_SOLICITADA NUMBER(25,3),
SOCO_TCONV_NU_ID NUMBER(19,0)
)
TABLESPACE "&TABLESPACE_DATOS";

COMMENT ON COLUMN "&USUARIO".AACI_SOLICITUD_CONCESION.SOCO_NU_ID IS 'Identificador primario de la tabla';
COMMENT ON COLUMN "&USUARIO".AACI_SOLICITUD_CONCESION.SOCO_NU_SOLICITUD IS 'Clave ajena de la solicitud';
COMMENT ON COLUMN "&USUARIO".AACI_SOLICITUD_CONCESION.SOCO_TX_TIPO_CONCESION IS 'Codigo del tipo concesion';
COMMENT ON COLUMN "&USUARIO".AACI_SOLICITUD_CONCESION.SOCO_NU_PRESUPUESTO_VALIDADO IS 'Presupuesto valiado para la solicitud dada';
COMMENT ON COLUMN "&USUARIO".AACI_SOLICITUD_CONCESION.SOCO_NU_SUBVENCION_SOLICITADA IS 'Subvencion solicitada para la solicitud dada';
COMMENT ON COLUMN "&USUARIO".AACI_SOLICITUD_CONCESION.SOCO_TCONV_NU_ID IS 'Codigo tipo de convocatoria a la que pertenece';

SPOOL OFF