SPOOL 02_AACID_OWNER_AACI_secuencias.log

DEF USUARIO= AACID_OWNER;

CREATE SEQUENCE "&USUARIO".AACI_SEQ_REFORMULA INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE "&USUARIO".AACI_SEQ_SOLICITUD_CONCESION INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE NOORDER;

SPOOL OFF