SPOOL 04_AACID_OWNER_AACI_constraints.log

DEF USUARIO=AACID_OWNER;
DEF TABLESPACE_INDICES=TS_I_AACID_OWNER;

ALTER TABLE "&USUARIO".AACI_REFORMULA ADD CONSTRAINT AACI_ID_REFORMULA_PK PRIMARY KEY ( ID_REFORMULA ) USING INDEX TABLESPACE "&TABLESPACE_INDICES";
ALTER TABLE "&USUARIO".AACI_REFORMULA ADD CONSTRAINT AACI_REFORMULA_SOLICITUD_FK FOREIGN KEY ( ID_SOLICITUD ) REFERENCES "&USUARIO".AACI_T_SOLICITUDSUBONGD ( ID_SOLICITUD ) ;


--Validacion Presupuesto--

ALTER TABLE "&USUARIO".AACI_TM_ENTIDAD_CONTRAPARTE ADD CONSTRAINT AACI_IDTMENTIDADCONTRAPARTE_PK PRIMARY KEY (TMEC_NU_ID) USING INDEX TABLESPACE "&TABLESPACE_INDICES";
ALTER TABLE "&USUARIO".AACI_CONTRAPARTES ADD CONSTRAINT FK_AACI_TM_ENTIDAD_CONTRAPARTE FOREIGN KEY (TMEC_NU_ID) REFERENCES "&USUARIO".AACI_TM_ENTIDAD_CONTRAPARTE (TMEC_NU_ID);



ALTER TABLE "&USUARIO".AACI_CON_OTRAS DROP CONSTRAINT FK_AACI_ENTIDAD;
ALTER TABLE "&USUARIO".AACI_CON_OTRAS ADD CONSTRAINT FK_AACI_ENTIDAD FOREIGN KEY(FK_ENTIDAD) REFERENCES "&USUARIO".AACI_ENTIDADES_PARTICIPANTES (ENPA_NU_ID);

ALTER TABLE "&USUARIO".AACI_SOLICITUD_CONCESION ADD CONSTRAINT FK_AACI_SOLICITUD_CONCESION FOREIGN KEY(SOCO_NU_SOLICITUD) REFERENCES "&USUARIO".AACI_T_SOLICITUDSUBONGD (ID_SOLICITUD);

SPOOL OFF