SPOOL 05_AACID_OWNER_AACI_grants.log

DEF USUARIO_OWNER=AACID_OWNER;
DEF USUARIO_USER=AACID_USER;

GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_REFORMULA TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_REFORMULA TO "&USUARIO_USER";

GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_SOLICITUD_CONCESION TO "&USUARIO_USER";
GRANT SELECT ON "&USUARIO_OWNER".AACI_SEQ_SOLICITUD_CONCESION TO "&USUARIO_USER";

GRANT DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_TM_ENTIDAD_CONTRAPARTE TO "&USUARIO_USER";

SPOOL OFF