SPOOL 06_AACID_USER_AACI_sinonimos.log

DEF USUARIO_OWNER=AACID_OWNER;
DEF USUARIO_USER=AACID_USER;


CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_REFORMULA FOR "&USUARIO_OWNER".AACI_SEQ_REFORMULA;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_REFORMULA FOR "&USUARIO_OWNER".AACI_REFORMULA;

CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SEQ_SOLICITUD_CONCESION FOR "&USUARIO_OWNER".AACI_SEQ_SOLICITUD_CONCESION;
CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_SOLICITUD_CONCESION FOR "&USUARIO_OWNER".AACI_SOLICITUD_CONCESION;

CREATE OR REPLACE SYNONYM "&USUARIO_USER".AACI_TM_ENTIDAD_CONTRAPARTE FOR "&USUARIO_OWNER".AACI_TM_ENTIDAD_CONTRAPARTE;

SPOOL OFF