SPOOL 03_AACID_OWNER_AACI_inserts.log

DEF USUARIO=AACID_OWNER;

insert into "&USUARIO".AACI_T_PAISES_SOLICITUD (ID_SOLICITUD, ID_PAIS, ID_PAIS_SOLICITUD) VALUES (321, 21, "&USUARIO".AACI_SEQ_PAISES_SOLICITUD.nextVal);

commit;

SPOOL OFF