SPOOL 11_AACID_OWNER_AACI_tablas.log

DEF USUARIO=AACID_OWNER;

ALTER TABLE "&USUARIO".AACI_SOLICITUD_CONCESION ADD SOCO_NU_SUBVENCION_CONCEDER NUMBER(25,3);

COMMENT ON COLUMN "&USUARIO".AACI_SOLICITUD_CONCESION.SOCO_NU_SUBVENCION_CONCEDER IS 'Subvencion a conceder para la solicitud dada';

SPOOL OFF