SPOOL 13_AACID_OWNER_AACI_tablas.log
    
DEF USUARIO=AACID_OWNER;
DEF TABLESPACE_DATOS=TS_D_AACID_OWNER;


CREATE TABLE "&USUARIO".AACI_SOLICITUD_CONCESION
(SOCO_NU_ID NUMBER(19,0),
SOCO_NU_SOLICITUD NUMBER(19,0),
SOCO_TX_TIPO_CONCESION VARCHAR(25),
SOCO_NU_PRESUPUESTO_VALIDADO NUMBER(25,3),
SOCO_NU_SUBVENCION_SOLICITADA NUMBER(25,3),
SOCO_TCONV_NU_ID NUMBER(19,0)
)
TABLESPACE "&TABLESPACE_DATOS";

COMMENT ON COLUMN "&USUARIO".AACI_SOLICITUD_CONCESION.SOCO_NU_ID IS 'Identificador primario de la tabla';
COMMENT ON COLUMN "&USUARIO".AACI_SOLICITUD_CONCESION.SOCO_NU_SOLICITUD IS 'Clave ajena de la solicitud';
COMMENT ON COLUMN "&USUARIO".AACI_SOLICITUD_CONCESION.SOCO_TX_TIPO_CONCESION IS 'Codigo del tipo concesion';
COMMENT ON COLUMN "&USUARIO".AACI_SOLICITUD_CONCESION.SOCO_NU_PRESUPUESTO_VALIDADO IS 'Presupuesto valiado para la solicitud dada';
COMMENT ON COLUMN "&USUARIO".AACI_SOLICITUD_CONCESION.SOCO_NU_SUBVENCION_SOLICITADA IS 'Subvencion solicitada para la solicitud dada';
COMMENT ON COLUMN "&USUARIO".AACI_SOLICITUD_CONCESION.SOCO_TCONV_NU_ID IS 'Codigo tipo de convocatoria a la que pertenece';

SPOOL OFF