SPOOL 12_AACID_OWNER_AACI_inserts.log

DEF USUARIO=AACID_OWNER;

update "&USUARIO".AACI_SOLICITUD_CONCESION set SOCO_TX_TIPO_CONCESION='Beneficiaria' where SOCO_TX_TIPO_CONCESION='Beneficiario ';
commit;

SPOOL OFF