SPOOL 01_AACID_OWNER_inserts_rollback.log

DEF USUARIO=AACID_OWNER;

delete from "&USUARIO".AACI_TM_CAPACIDAD_GESTION where TMCG_NU_ANIO = 2022;
delete from "&USUARIO".AACI_GASTOS ;
delete from "&USUARIO".AACI_GASTOS_FINALIDAD ;
delete from "&USUARIO".AACI_FUNCIONES ;
delete from "&USUARIO".AACI_T_ENTIDAD_PARTICIPANTE ;

SPOOL OFF