SPOOL 02_AACID_OWNER_tablas_rollback.log

DEF USUARIO=AACID_OWNER;

DROP TABLE "&USUARIO".AACI_T_DOCUMENTO_EXPEDIENTE CASCADE CONSTRAINTS;

alter table "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_ALEGO;
alter table "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN TX_ALEGO;
alter table "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN LG_OTRO_ALEGO;
alter table "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN TX_OTRO_ALEGO;
alter table "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN TX_COD_DIR3;
alter table "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN TX_REPR1_EMAIL;
alter table "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN TX_REPR1_TELEFONO;
alter table "&USUARIO".AACI_T_SOLICITUDSUBONGD DROP COLUMN TX_REPR1_TLFMOVIL;
alter table "&USUARIO".AACI_TM_CAPACIDAD_GESTION DROP COLUMN TMCG_NU_ANIO;
alter table "&usuario".AACI_GASTOS_FINALIDAD DROP COLUMN GAST_NU_ID;

SPOOL OFF