SPOOL 03_AACID_OWNER_secuencias_rollback.log

DEF USUARIO=AACID_OWNER;

DROP SEQUENCE "&USUARIO".AACI_SEQ_DOCUMENTO_EXPEDIENTE;
DROP SEQUENCE "&USUARIO".AACI_SEQ_GASTOS;
DROP SEQUENCE "&USUARIO".AACI_SEQ_GASTOS_FINALIDAD;
DROP SEQUENCE "&USUARIO".AACI_SEQ_FUNCIONES;
DROP SEQUENCE "&USUARIO".AACI_SEQ_T_ENT_PARTICIPANTE;

SPOOL OFF