SPOOL 04_AACID_OWNER_revoke.log

DEF USUARIO_OWNER=AACID_OWNER;
DEF USUARIO_USER=AACID_USER;

REVOKE SELECT ON "&USUARIO_OWNER".AACI_SEQ_DOCUMENTO_EXPEDIENTE FROM "&USUARIO_USER";
REVOKE DELETE, INSERT, UPDATE, SELECT ON "&USUARIO_OWNER".AACI_T_DOCUMENTO_EXPEDIENTE FROM "&USUARIO_USER";
REVOKE SELECT ON "&USUARIO_OWNER".AACI_SEQ_GASTOS FROM "&USUARIO_USER";
REVOKE SELECT ON "&USUARIO_OWNER".AACI_SEQ_GASTOS_FINALIDAD FROM "&USUARIO_USER";
REVOKE SELECT ON "&USUARIO_OWNER".AACI_SEQ_FUNCIONES FROM "&USUARIO_USER";
REVOKE SELECT ON "&USUARIO_OWNER".AACI_SEQ_T_ENT_PARTICIPANTE FROM "&USUARIO_USER";

SPOOL OFF